// =============================================================================
// Complex phrases for Pictionary / Telephone-Draw
// A mix of ~1000 hand-curated phrases and ~4000 generated combinations
// Total: exactly 5000 unique, funny, drawable phrases
// =============================================================================

// ---------------------------------------------------------------------------
// 1. Hand-curated creative phrases (~1000)
// ---------------------------------------------------------------------------
const curatedPhrases: string[] = [
  // Classic absurd scenarios
  "astronaut riding a horse",
  "dancing in the rain",
  "ninja cat",
  "robot doing yoga",
  "penguin in a business suit",
  "dinosaur at a job interview",
  "wizard making breakfast",
  "ghost trying to high five",
  "pirate on a skateboard",
  "alien doing laundry",
  "dragon blowing out birthday candles",
  "mermaid in a desert",
  "zombie at a spa day",
  "cowboy riding a shark",
  "knight fighting a toaster",
  "vampire at the beach",
  "santa on summer vacation",
  "yeti in a hot tub",
  "leprechaun at the gym",
  "genie stuck in traffic",

  // Animals doing human things
  "cat filing taxes",
  "dog walking a human",
  "goldfish driving a car",
  "hamster lifting weights",
  "parrot giving a ted talk",
  "sloth running a marathon",
  "elephant tiptoeing",
  "octopus playing piano",
  "snake wearing boots",
  "penguin surfing",
  "frog in a tuxedo",
  "bear doing ballet",
  "horse on a pogo stick",
  "duck in sunglasses",
  "owl working night shift",
  "koala on a coffee break",
  "giraffe on a roller coaster",
  "hippo in a tutu",
  "raccoon stealing wifi",
  "squirrel hoarding bitcoin",

  // Food-related chaos
  "pizza delivering itself",
  "spaghetti tornado",
  "taco riding a burrito",
  "ice cream melting in horror",
  "banana slipping on a person",
  "donut rolling down a hill",
  "sushi on a date",
  "hot dog at a costume party",
  "cookie monster at a diet clinic",
  "popcorn at a scary movie",
  "avocado toast proposal",
  "bread rising to the occasion",
  "cheese wheel racing",
  "cupcake rebellion",
  "french fry skydiving",
  "pancake stack yoga",
  "watermelon surfing",
  "pickle in a jar escape",
  "egg walking on eggshells",
  "broccoli hiding from a child",

  // Everyday objects gone wild
  "alarm clock running away",
  "sock escaping the dryer",
  "remote control rebellion",
  "chair playing musical chairs",
  "umbrella in a drought",
  "toaster taking a bath",
  "lamp having a bright idea",
  "pillow in a pillow fight",
  "broom sweeping the competition",
  "scissors running with scissors",
  "pencil drawing itself",
  "mirror looking at itself",
  "clock killing time",
  "door slamming itself",
  "window of opportunity closing",
  "bed making itself",
  "toilet flushing with pride",
  "fridge running",
  "stairway to heaven",
  "elevator music band",

  // Pop culture mashups
  "darth vader at disneyland",
  "batman at a therapist",
  "superman doing laundry",
  "godzilla in new york traffic",
  "king kong on a tinder date",
  "frankenstein at a beauty salon",
  "dracula donating blood",
  "medusa at the hair salon",
  "thor using his hammer for nails",
  "hulk doing pottery",
  "sherlock solving a jigsaw puzzle",
  "gandalf at airport security",
  "yoda teaching grammar",
  "james bond making tea",
  "indiana jones at ikea",
  "mary poppins skydiving",
  "tarzan in a business meeting",
  "cinderella losing her phone",
  "jack sparrow in a canoe",
  "robin hood filing taxes",

  // Professions in wrong places
  "dentist on a deserted island",
  "teacher on the moon",
  "chef in a zero gravity kitchen",
  "firefighter underwater",
  "pilot afraid of heights",
  "lifeguard in a desert",
  "mailman delivering to mars",
  "doctor afraid of blood",
  "plumber in space",
  "electrician in the dark ages",
  "accountant counting stars",
  "lawyer defending a cat",
  "detective solving a missing sock case",
  "scientist in a bouncy castle",
  "mechanic fixing a horse",
  "barber cutting a hedge",
  "photographer in a blackout",
  "musician in a library",
  "farmer on a rooftop",
  "athlete sleeping in",

  // Weather and nature absurdity
  "thunderstorm in a teacup",
  "tornado in a snow globe",
  "tsunami in a bathtub",
  "earthquake at a yoga class",
  "avalanche of teddy bears",
  "rainbow in black and white",
  "volcano erupting marshmallows",
  "hurricane of butterflies",
  "blizzard of confetti",
  "meteor shower of meatballs",
  "lightning striking twice",
  "flood of chocolate milk",
  "hailstorm of golf balls",
  "sandstorm in a living room",
  "fog of confusion",
  "dewdrop on a spider web",
  "frost on a tropical island",
  "heatwave at the north pole",
  "monsoon in a phone booth",
  "whirlpool in a coffee cup",

  // Time travel scenarios
  "caveman with a smartphone",
  "dinosaur in modern traffic",
  "medieval knight at a drive through",
  "roman gladiator at the olympics",
  "victorian lady on a hoverboard",
  "ancient egyptian with a selfie stick",
  "viking at a buffet",
  "samurai at a sushi restaurant",
  "pilgrim at black friday",
  "neanderthal at a salon",
  "pharaoh in a jacuzzi",
  "aztec warrior playing video games",
  "pirate ordering uber",
  "cowboy at a robot rodeo",
  "flapper dancer at a rave",
  "hippie at a corporate meeting",
  "disco dancer at a funeral",
  "beatnik at a poetry slam",
  "victorian gentleman skateboarding",
  "renaissance painter using photoshop",

  // Emotional objects
  "sad cloud crying rain",
  "happy sun wearing sunglasses",
  "angry volcano screaming",
  "lonely planet in space",
  "excited electron",
  "depressed couch potato",
  "anxious clock watching itself",
  "jealous green monster",
  "confused compass",
  "proud peacock in a mirror",
  "embarrassed tomato turning red",
  "scared shadow",
  "bored black hole",
  "curious cat in a box",
  "optimistic balloon rising",
  "pessimistic rain cloud",
  "nostalgic cassette tape",
  "love struck arrow through a heart",
  "grumpy morning alarm",
  "zen rock meditating",

  // Sports gone wrong
  "bowling with coconuts",
  "golf on the moon",
  "surfing on lava",
  "ice skating on butter",
  "rock climbing a sandwich",
  "swimming through jello",
  "skiing down a pyramid",
  "wrestling with your conscience",
  "boxing with pillows",
  "fencing with breadsticks",
  "archery with bananas",
  "basketball in zero gravity",
  "soccer with a boulder",
  "tennis with frying pans",
  "marathon through quicksand",
  "gymnastics on a trampoline cloud",
  "weightlifting feathers",
  "rowing in a bathtub",
  "hurdles over sleeping cats",
  "javelin throw with a baguette",

  // Music and art chaos
  "orchestra of cats",
  "heavy metal lullaby",
  "karaoke with a whale",
  "drumming on pots and pans",
  "air guitar championship",
  "conducting lightning",
  "playing violin with spaghetti",
  "rapping grandma",
  "opera singer breaking glass",
  "DJ spinning a pizza",
  "painting with ketchup",
  "sculpting with mashed potatoes",
  "graffiti artist on the moon",
  "tap dancing on a keyboard",
  "ballet in a mosh pit",
  "jazz hands at a funeral",
  "yodeling in a library",
  "beatboxing robot",
  "harmonica in a hurricane",
  "triangle solo",

  // Technology mishaps
  "robot learning to love",
  "computer catching a cold",
  "smartphone taking a selfie",
  "printer jamming to music",
  "wifi signal searching for meaning",
  "bluetooth looking for a tooth",
  "GPS getting lost",
  "autocorrect ruining a love letter",
  "firewall fighting actual fire",
  "cloud computing in the rain",
  "virus wearing a tiny mask",
  "mouse clicking on a cat",
  "keyboard warrior typing in armor",
  "screensaver saving a life",
  "backup dancer backing up data",
  "streaming a literal river",
  "downloading a car",
  "uploading a cat to the cloud",
  "debugging an actual bug",
  "rebooting a boot",

  // Fantasy meets reality
  "unicorn in rush hour",
  "dragon at a barbecue",
  "troll under a highway overpass",
  "fairy godmother with a broken wand",
  "elf doing overtime at christmas",
  "ogre at a beauty pageant",
  "centaur at the shoe store",
  "phoenix at a fire station",
  "kraken in a kiddie pool",
  "griffin through airport security",
  "minotaur in a maze corn field",
  "cyclops at the eye doctor",
  "werewolf at a full moon party",
  "banshee at a silent disco",
  "gorgon at a selfie museum",
  "pixie dust allergy",
  "magic carpet through a car wash",
  "enchanted forest fire drill",
  "potion class chemistry lab",
  "spell check wizard",

  // Space adventures
  "barbecue on the sun",
  "fishing in the milky way",
  "gardening on mars",
  "road trip through the asteroid belt",
  "picnic on saturn's rings",
  "snowboarding on pluto",
  "laundry on the international space station",
  "traffic jam in a wormhole",
  "camping on a comet",
  "stargazing from a star",
  "black hole vacation",
  "alien pen pal",
  "moon bouncing literally",
  "mars rover road rage",
  "venus fly trap on venus",
  "jupiter's great red spot cream",
  "neptune's trident selfie",
  "space junk yard sale",
  "solar flare up temper",
  "constellation connect the dots",

  // Office life absurdity
  "spreadsheet coming to life",
  "meeting that could have been an email",
  "coffee machine uprising",
  "stapler hostage situation",
  "water cooler gossip tornado",
  "monday morning zombie walk",
  "friday afternoon escape plan",
  "deadline approaching literally",
  "boss battle in the boardroom",
  "promotion celebration in space",
  "performance review from a cat",
  "team building on a volcano",
  "brainstorm actual storm",
  "lunch break prison escape",
  "email avalanche",
  "powerpoint karate",
  "cubicle fort defense",
  "parking lot thunder dome",
  "elevator pitch in an elevator",
  "casual friday on mars",

  // Childhood nostalgia gone wild
  "tooth fairy union strike",
  "easter bunny at the gym",
  "sandcastle siege",
  "blanket fort diplomacy",
  "imaginary friend real estate",
  "monster under the bed paying rent",
  "treehouse penthouse",
  "swing set to outer space",
  "lego stepping stone path",
  "bubble wrap meditation",
  "playground revolution",
  "juice box sommelier",
  "nap time uprising",
  "coloring outside the universe",
  "hide and seek champion since 1995",
  "show and tell black hole",
  "recess warrior",
  "bedtime story horror edition",
  "night light disco",
  "stuffed animal parliament",

  // Cooking catastrophes
  "flambé gone wrong",
  "soufflé in an earthquake",
  "cooking show explosion",
  "recipe for disaster literally",
  "microwave time machine",
  "oven mitt boxing match",
  "whisk tornado",
  "rolling pin bowling",
  "salt shaker rain dance",
  "pepper grinder pepper spray",
  "blender smoothie hurricane",
  "toaster launching bread rockets",
  "deep fryer volcano",
  "spatula sword fight",
  "measuring cup precision archery",
  "colander helmet warrior",
  "apron cape superhero",
  "pot and pan drum circle",
  "cutting board surfing",
  "kitchen timer bomb defusal",

  // Transportation madness
  "bicycle with square wheels",
  "submarine in the sky",
  "airplane underwater",
  "train going in circles",
  "helicopter with a propeller hat",
  "skateboard with rockets",
  "canoe in a swimming pool",
  "hot air balloon indoors",
  "segway chariot race",
  "unicycle on a tightrope",
  "tricycle gang",
  "school bus monster truck",
  "ice cream truck chase",
  "shopping cart derby",
  "wheelchair stunt jump",
  "scooter jousting",
  "wagon trail through a mall",
  "hovercraft in a parking lot",
  "gondola in the sewer",
  "rickshaw formula one",

  // Seasonal silliness
  "snowman on a tropical beach",
  "jack o lantern year round",
  "christmas tree in july",
  "cupid with bad aim",
  "turkey pardoning the president",
  "new years resolution quitting day two",
  "groundhog day time loop",
  "april fools gone too far",
  "mothers day breakfast catastrophe",
  "fathers day tie collection",
  "valentines day lonely cactus",
  "halloween costume malfunction",
  "thanksgiving food coma",
  "independence day firework oops",
  "labor day actual labor",
  "memorial day memory loss",
  "st patricks day green everything",
  "earth day guilt trip",
  "tax day horror movie",
  "birthday party for a ghost",

  // Dream and nightmare fuel
  "falling in a dream within a dream",
  "teeth falling out at a party",
  "showing up to school in pajamas",
  "flying but forgetting how to land",
  "being chased by a giant rubber duck",
  "underwater tea party",
  "clouds made of cotton candy",
  "riding a rainbow slide",
  "gravity switching directions",
  "talking to your reflection",
  "shrinking to ant size",
  "growing to giant size at dinner",
  "walking through walls into walls",
  "time moving backwards",
  "colors tasting like sounds",
  "floating furniture room",
  "staircase going nowhere",
  "door opening to another dimension",
  "raining cats and dogs literally",
  "snow made of powdered sugar",

  // Historical figures in modern times
  "cleopatra at a shopping mall",
  "napoleon at a buffet",
  "da vinci with a tablet",
  "einstein on a skateboard",
  "mozart with headphones",
  "shakespeare tweeting",
  "julius caesar at a salad bar",
  "alexander the great at mini golf",
  "genghis khan at a petting zoo",
  "queen elizabeth at a water park",
  "columbus with a gps",
  "beethoven at a rave",
  "michelangelo painting a ceiling fan",
  "galileo with a telescope selfie",
  "nero fiddling with his phone",
  "aristotle at a bar arguing",
  "socrates asking too many questions at a cafe",
  "marco polo in a swimming pool",
  "henry the eighth on a dating app",
  "ben franklin flying a kite in a thunderstorm selfie",

  // Superhero problems
  "superman stuck in revolving door",
  "batman afraid of bats",
  "spider man with arachnophobia",
  "invisible woman losing her keys",
  "flash stuck in slow motion",
  "aquaman in a desert",
  "wonder woman at the dmv",
  "hulk assembling ikea furniture",
  "iron man with a wrinkled suit",
  "captain america doing taxes",
  "wolverine at a manicure",
  "storm creating a drizzle",
  "cyclops at a 3d movie",
  "magneto at a metal detector",
  "professor x forgetting something",
  "ant man at a picnic",
  "black panther herding cats",
  "doctor strange at a normal hospital",
  "green lantern changing a lightbulb",
  "hawkeye at an archery lesson",

  // Animals with jobs
  "shark accountant",
  "penguin crossing guard",
  "dolphin lifeguard",
  "monkey mechanic",
  "panda chef",
  "flamingo traffic cop",
  "chameleon spy",
  "turtle delivery driver",
  "kangaroo postal worker",
  "beaver architect",
  "crow lawyer",
  "ant construction worker",
  "bee stockbroker",
  "butterfly weather reporter",
  "eagle airline pilot",
  "fox news anchor",
  "goat yoga instructor",
  "hedgehog acupuncturist",
  "iguana interior designer",
  "jellyfish electrician",

  // Absurd competitions
  "competitive napping",
  "extreme ironing on a mountain",
  "underwater chess",
  "speed walking on the moon",
  "cheese rolling championship",
  "toe wrestling world cup",
  "pillow fight tournament",
  "snail racing grand prix",
  "competitive eyebrow raising",
  "thumb war world championship",
  "rock paper scissors olympics",
  "staring contest with a statue",
  "synchronized swimming in puddles",
  "long distance paper airplane throw",
  "speed eating contest in slow motion",
  "musical chairs death match",
  "tug of war with a mountain",
  "hide and seek in an empty room",
  "hot dog eating contest for vegetarians",
  "limbo under a rainbow",

  // Impossible scenarios
  "herding cats in zero gravity",
  "knitting with spaghetti",
  "building sandcastle in a hurricane",
  "whispering in a tornado",
  "reading in the dark",
  "ice skating on the sun",
  "sunbathing at night",
  "fishing in a bathtub",
  "mountain climbing a molehill",
  "deep sea diving in a puddle",
  "parachuting indoors",
  "camping in a living room",
  "safari in a pet store",
  "treasure hunting in a junk drawer",
  "whale watching in a fish tank",
  "stargazing in a planetarium",
  "bird watching with binoculars backwards",
  "storm chasing a gentle breeze",
  "volcano watching from inside",
  "earthquake proof jello building",

  // Mashup creatures
  "shark with eagle wings",
  "cat with octopus tentacles",
  "dog with butterfly wings",
  "elephant with giraffe neck",
  "penguin with kangaroo legs",
  "turtle with cheetah speed",
  "rabbit with rhino horn",
  "frog with flamingo legs",
  "pig with peacock feathers",
  "fish with spider legs",
  "snake with arms",
  "bear with duck feet",
  "lion with jellyfish mane",
  "horse with propeller",
  "monkey with crab claws",
  "owl with bat wings",
  "wolf with porcupine quills",
  "deer with lobster antlers",
  "fox with scorpion tail",
  "mouse with moose antlers",

  // Everyday life plot twists
  "alarm clock that plays heavy metal",
  "traffic light that only shows purple",
  "elevator that goes sideways",
  "doorbell that tells jokes",
  "refrigerator that judges your choices",
  "washing machine eating socks",
  "vacuum cleaner afraid of dust",
  "lawn mower on strike",
  "dishwasher demanding a raise",
  "garage door with stage fright",
  "thermostat with mood swings",
  "ceiling fan doing the wave",
  "smoke detector at a barbecue",
  "sprinkler system at a pool party",
  "mailbox with a full inbox",
  "garbage truck at a perfume counter",
  "fire hydrant in a drought",
  "traffic cone on a date",
  "parking meter running out of time",
  "speed bump getting revenge",

  // Science gone silly
  "atom splitting at a breakup",
  "molecule having a bond moment",
  "electron losing its charge",
  "proton being positive about everything",
  "neutron staying neutral in an argument",
  "gravity taking a day off",
  "evolution of a couch potato",
  "photosynthesis at a nightclub",
  "mitosis in a crowded elevator",
  "entropy at an organizing convention",
  "black hole on a diet",
  "supernova gender reveal",
  "big bang at a quiet library",
  "quantum physics cat alive and dead",
  "chemistry between two flasks",
  "biology class dissecting homework",
  "physics dropping the ball",
  "astronomy starstruck",
  "geology taking things for granite",
  "mathematics unable to even",

  // Fashion disasters
  "socks with sandals on a runway",
  "cape made of bubble wrap",
  "hat made of cheese",
  "shoes made of glass at a marathon",
  "belt made of a snake",
  "scarf made of spaghetti",
  "dress made of newspapers",
  "tie made of licorice",
  "jacket made of bubble gum",
  "pants made of duct tape",
  "crown made of french fries",
  "gloves made of cactus",
  "boots made of jello",
  "vest made of playing cards",
  "sunglasses made of donuts",
  "necklace made of pretzels",
  "earrings made of fishing lures",
  "bracelet made of tiny hot dogs",
  "headband made of gummy worms",
  "toga made of toilet paper",

  // Misunderstood idioms
  "raining cats and dogs in a shelter",
  "breaking a leg on stage literally",
  "elephant in the room at a party",
  "skeleton in the closet coming out",
  "cat got your tongue at a vet",
  "piece of cake eating itself",
  "spill the beans at a restaurant",
  "let the cat out of the bag surprise",
  "barking up the wrong tree",
  "biting off more than you can chew contest",
  "burning the midnight oil lamp",
  "butterflies in your stomach x-ray",
  "crying over spilled milk cleanup",
  "hitting the nail on the head literally",
  "jumping on the bandwagon",
  "killing two birds with one stone detective",
  "letting sleeping dogs lie in court",
  "opening a can of worms fishing",
  "putting all eggs in one basket juggler",
  "wolf in sheep clothing at a farm",

  // Tiny things being big
  "ant lifting a house",
  "mouse scaring an elephant",
  "ladybug moving a car",
  "grain of sand building a mountain",
  "raindrop causing a flood",
  "snowflake starting an avalanche",
  "spark starting a wildfire",
  "whisper causing an echo",
  "pebble causing an earthquake",
  "feather tipping a scale",
  "crumb feeding an army",
  "pixel creating a masterpiece",
  "stitch saving nine",
  "penny making a fortune",
  "seed growing a forest",
  "note becoming a symphony",
  "step beginning a journey",
  "thought changing the world",
  "smile lighting up a room",
  "tear filling an ocean",

  // Big things being tiny
  "whale in a fishbowl",
  "elephant in a matchbox",
  "sun in a snow globe",
  "mountain in a backpack",
  "ocean in a teacup",
  "galaxy in a marble",
  "dinosaur in a birdcage",
  "tornado in a jar",
  "redwood in a flower pot",
  "skyscraper in a dollhouse",
  "aircraft carrier in a bathtub",
  "planet in a pocket",
  "volcano in a cupcake",
  "glacier in a freezer",
  "continent on a plate",
  "comet in a lunchbox",
  "tsunami in a glass of water",
  "avalanche in a sandbox",
  "black hole in a donut",
  "supernova in a lightbulb",

  // Unexpected duets
  "cat and dog sharing an umbrella",
  "fire and ice cream on a date",
  "sun and moon having lunch",
  "robot and butterfly painting together",
  "ghost and skeleton roommates",
  "pirate and ninja at a peace treaty",
  "angel and devil playing cards",
  "alien and bigfoot taking a selfie",
  "vampire and garlic bread making up",
  "witch and scientist collaborating",
  "king and jester switching roles",
  "teacher and student both confused",
  "hero and villain at couples therapy",
  "past and future meeting for coffee",
  "mountain and valley high fiving",
  "desert and ocean switching places",
  "thunder and lightning in a band",
  "rainbow and storm having a truce",
  "day and night sharing a scarf",
  "summer and winter arm wrestling",

  // Weird inventions
  "umbrella for fish",
  "sunglasses for bats",
  "shoes for snakes",
  "helmet for giraffe",
  "parachute for a penguin",
  "life jacket for a whale",
  "doorbell for a cave",
  "escalator for ants",
  "elevator for birds",
  "car horn for a bicycle",
  "flashlight for the sun",
  "alarm clock for a rooster",
  "bookmark for a kindle",
  "raincoat for a duck",
  "heater for the desert",
  "snowplow for the beach",
  "submarine screen door",
  "solar powered flashlight",
  "waterproof sponge",
  "inflatable dartboard",

  // Miscellaneous creative phrases (filling to ~1000)
  "cloud nine eviction notice",
  "bermuda triangle lost and found",
  "fountain of youth senior discount",
  "garden gnome revolution",
  "loch ness monster at a pool party",
  "bigfoot footprint casting call",
  "crop circle art gallery",
  "bermuda shorts in the bermuda triangle",
  "four leaf clover audit",
  "pot of gold ira account",
  "magic eight ball tech support",
  "crystal ball software update",
  "fortune teller spoiler alert",
  "voodoo doll acupuncture",
  "ouija board autocorrect",
  "lucky horseshoe at the casino",
  "rabbits foot marathon runner",
  "wishing well venture capital",
  "shooting star paparazzi",
  "northern lights disco ball",

  "quicksand slow dance",
  "tumbleweed race",
  "mirage oasis resort",
  "echo chamber debate club",
  "shadow puppet theater critic",
  "dust bunny ranch",
  "lint roller at a fur convention",
  "rubber duck navy",
  "bubble bath submarine",
  "pillow fortress siege",
  "blanket cape superhero",
  "cardboard box spaceship",
  "paper airplane first class",
  "tin foil hat fashion show",
  "rubber band orchestra",
  "paper clip chain gang",
  "sticky note novel",
  "tape dispenser DJ",
  "stapler shark",
  "hole puncher confetti maker",

  "cactus hug",
  "porcupine pillow",
  "venus flytrap restaurant",
  "tumbleweed pet owner",
  "dandelion wish factory",
  "sunflower solar panel",
  "bamboo construction crew",
  "ivy league wall climber",
  "moss carpet installer",
  "mushroom apartment complex",
  "fern interior decorator",
  "rose thorn security guard",
  "lily pad ferry service",
  "seaweed hair salon",
  "coral reef city planner",
  "driftwood furniture store",
  "petrified forest museum",
  "quicksand lifeguard",
  "tar pit theme park",
  "geyser coffee maker",

  "dream catcher customer service",
  "time capsule unboxing video",
  "snow globe maintenance worker",
  "lava lamp interior designer",
  "mood ring therapist",
  "magic carpet uber driver",
  "crystal ball weather forecast",
  "treasure chest storage unit",
  "message in a bottle email",
  "compass with no direction",
  "telescope looking backwards",
  "hourglass overtime",
  "sundial in a tunnel",
  "weathervane on a treadmill",
  "metronome at a jazz club",
  "kaleidoscope optometrist",
  "prism splitting a rainbow",
  "pendulum decision maker",
  "magnifying glass detective ant",
  "periscope at a concert",

  "sock puppet government",
  "hand puppet job interview",
  "marionette cutting its own strings",
  "ventriloquist dummy uprising",
  "jack in the box therapist",
  "russian nesting doll family reunion",
  "bobblehead earthquake survivor",
  "snow globe shaking itself",
  "music box wind up marathon",
  "cuckoo clock overtime shift",
  "whoopee cushion at a board meeting",
  "joy buzzer electrician",
  "fake mustache spy",
  "x ray specs optometrist",
  "invisible ink love letter",
  "trick candles birthday rage",
  "rubber chicken restaurant critic",
  "foam finger pointing the way",
  "novelty glasses disguise",
  "squirting flower gardener",

  "suitcase packing itself",
  "passport photo glow up",
  "boarding pass to the moon",
  "hotel room for ghosts",
  "room service for monsters",
  "luggage carousel carousel",
  "airport runway fashion show",
  "flight attendant on a magic carpet",
  "customs declaring alien artifacts",
  "duty free shop on a pirate ship",
  "lost baggage in another dimension",
  "jet lag time traveler",
  "turbulence dance party",
  "layover at the bermuda triangle",
  "first class in a cardboard box",
  "window seat into another world",
  "overhead bin portal",
  "tray table dinner date",
  "seat belt on a roller coaster",
  "emergency exit into narnia",

  "mime trapped in an actual box",
  "clown at a serious meeting",
  "acrobat doing housework",
  "juggler at a grocery store",
  "magician failing at real magic",
  "contortionist in a small car",
  "tightrope walker crossing the street",
  "trapeze artist on a swing set",
  "sword swallower at dinner",
  "fire breather at a birthday party",
  "strongman opening a jar",
  "ringmaster at a circus of cats",
  "escape artist in an escape room",
  "human cannonball commute",
  "bearded lady at a barber",
  "stilt walker in a low ceiling room",
  "lion tamer with kittens",
  "knife thrower playing darts",
  "unicyclist in traffic",
  "balloon animal veterinarian",

  "library of unfinished books",
  "museum of broken promises",
  "gallery of invisible art",
  "theater of awkward silences",
  "stadium of competitive sleeping",
  "arena of polite disagreements",
  "park of anxious birds",
  "zoo of extinct animals",
  "aquarium of flying fish",
  "garden of electric flowers",
  "maze of mirrors and doors",
  "castle of bouncy walls",
  "tower of leaning pizza",
  "bridge of musical notes",
  "tunnel of cheese",
  "cave of glowing mushrooms",
  "island of misfit socks",
  "forest of candy trees",
  "desert of frozen yogurt",
  "swamp of bubblegum",

  "speed dating for turtles",
  "couples therapy for salt and pepper",
  "family reunion for elements",
  "baby shower for a thundercloud",
  "retirement party for a boomerang",
  "graduation for a caterpillar",
  "wedding between ketchup and mustard",
  "divorce between peanut butter and jelly",
  "first date between a fork and spoon",
  "anniversary of left and right sock",
  "blind date between day and night",
  "class reunion for crayons",
  "neighborhood watch for garden gnomes",
  "book club for bookworms literally",
  "support group for used batteries",
  "anger management for volcanos",
  "group therapy for broken clocks",
  "intervention for a sugar addict donut",
  "rehab for a bouncy ball",
  "self help seminar for mirrors",
];

// ---------------------------------------------------------------------------
// 2. Building-block arrays for generated combinations
// ---------------------------------------------------------------------------

const adjectives: string[] = [
  "giant", "tiny", "flying", "invisible", "dancing", "angry", "sleepy",
  "magical", "robotic", "flaming", "frozen", "electric", "bouncy", "glowing",
  "sparkly", "grumpy", "cheerful", "sneaky", "clumsy", "elegant",
  "furious", "gentle", "haunted", "jazzy", "legendary", "mysterious",
  "nervous", "obsessed", "polite", "quiet", "reckless", "sarcastic",
  "timid", "unstoppable", "vengeful", "wicked", "zealous", "bewildered",
  "caffeinated", "dramatic", "enchanted", "fearless", "goofy", "heroic",
  "itchy", "jolly", "kooky", "lazy", "melodramatic", "naughty",
  "overconfident", "panicking", "quirky", "rowdy", "suspicious", "theatrical",
  "unimpressed", "villainous", "whimsical", "exhausted", "yawning", "zany",
  "ancient", "baby", "cosmic", "dizzy", "enormous", "fancy", "glamorous",
  "hyperactive", "icy", "jumbo", "karate", "luminous", "miniature",
  "neon", "organic", "plaid", "radioactive", "supersonic", "turbo",
  "underwater", "volcanic", "wealthy", "x-ray", "yelling", "zombie",
  "armored", "buff", "crystal", "disco", "exploding", "feathered",
  "golden", "holographic", "inflatable", "jet-powered", "knitted",
  "levitating", "multi-armed", "ninja", "origami", "punk", "quantum",
  "rubbery", "steampunk", "telepathic", "upside-down", "velvet",
  "woolly", "bedazzled", "pixelated", "translucent", "rainbow",
  "spring-loaded", "solar-powered", "time-traveling", "shape-shifting",
  "fire-breathing", "mind-reading", "tap-dancing", "beatboxing",
  "opera-singing", "skateboarding", "surfing", "hula-hooping",
  "breakdancing", "moonwalking", "salsa-dancing",
];

const creatures: string[] = [
  "cat", "dragon", "robot", "unicorn", "dinosaur", "alien", "wizard",
  "pirate", "penguin", "monkey", "shark", "bear", "octopus", "ghost",
  "vampire", "zombie", "werewolf", "mermaid", "phoenix", "griffin",
  "yeti", "centaur", "minotaur", "sphinx", "kraken", "goblin",
  "troll", "ogre", "cyclops", "gargoyle", "golem", "chimera",
  "hydra", "basilisk", "leprechaun", "fairy", "gnome", "dwarf",
  "elf", "orc", "skeleton", "demon", "angel", "genie", "djinn",
  "sasquatch", "jackalope", "chupacabra", "thunderbird", "manticore",
  "hippogriff", "pegasus", "kelpie", "banshee", "poltergeist",
  "gorgon", "siren", "nymph", "dryad", "satyr", "pixie",
  "duck", "hamster", "llama", "panda", "sloth", "raccoon",
  "flamingo", "hedgehog", "corgi", "pug", "parrot", "turtle",
  "frog", "snail", "bee", "butterfly", "jellyfish", "starfish",
  "seahorse", "narwhal", "axolotl", "chameleon", "pangolin",
  "capybara", "red panda", "quokka", "wombat", "platypus",
  "walrus", "moose", "buffalo", "coyote", "fox", "wolf",
  "eagle", "owl", "raven", "falcon", "toucan", "pelican",
];

const actions: string[] = [
  "riding a bicycle", "eating pizza", "playing guitar", "doing yoga",
  "surfing", "baking cookies", "writing poetry", "painting a portrait",
  "juggling flaming torches", "doing stand-up comedy", "taking a selfie",
  "building a sandcastle", "flying a kite", "solving a rubiks cube",
  "arm wrestling", "doing a backflip", "reading a newspaper",
  "playing chess", "knitting a sweater", "riding a skateboard",
  "cooking dinner", "fixing a car", "walking a tightrope",
  "blowing bubbles", "catching fireflies", "climbing a ladder",
  "digging for treasure", "escaping a maze", "fishing with a net",
  "gardening on a roof", "hula hooping", "ice fishing",
  "jousting with a pool noodle", "kicking a field goal",
  "launching a paper airplane", "making pancakes", "nursing a coffee",
  "opening a stubborn jar", "practicing karate", "quilting a blanket",
  "racing a go-kart", "singing in the shower", "typing an email",
  "using chopsticks for the first time", "vacuuming the ocean",
  "washing a whale", "playing the xylophone",
  "yodeling from a mountaintop", "ziplining over a city",
  "assembling furniture", "bench pressing a couch",
  "conducting an orchestra", "debugging code", "eating cereal",
  "folding origami", "grilling burgers", "hitchhiking to mars",
  "ironing a shirt", "jumping rope", "kayaking",
  "learning to drive", "mopping the floor", "napping in a hammock",
  "ordering takeout", "playing drums", "questioning reality",
  "running a marathon", "skipping stones", "teaching a class",
  "unclogging a drain", "volunteering at a shelter",
  "walking on stilts", "playing the accordion",
  "yelling at clouds", "zooming on a call",
  "doing the macarena", "breakdancing", "moonwalking",
  "doing push-ups", "meditating",
  "competing in a staring contest",
  "giving a ted talk", "hosting a podcast",
];

const locations: string[] = [
  "on the moon", "underwater", "in a volcano", "at a disco",
  "in space", "on a cloud", "in a library", "at the north pole",
  "on a roller coaster", "in a haunted house", "at a food court",
  "on a pirate ship", "in a time machine", "at the beach",
  "on top of a skyscraper", "in a bouncy castle", "at a wedding",
  "in a submarine", "on a deserted island", "in a cave",
  "at a fancy restaurant", "on a train", "in the jungle",
  "at a rock concert", "on the great wall of china",
  "in a shopping mall", "at a rodeo", "on mount everest",
  "in a hot air balloon", "at a drive-in movie",
  "on a ferris wheel", "in a corn maze",
  "at an amusement park", "on a yacht", "in a treehouse",
  "at a bowling alley", "on a trampoline",
  "in a phone booth", "at a laundromat", "on a rooftop",
  "in a igloo", "at a gas station", "on a floating island",
  "in a castle dungeon", "at a farmers market",
  "on a magic carpet", "in a greenhouse", "at an art museum",
  "on a race track", "in a snowstorm",
  "at a campfire", "on a moving truck", "in a bakery",
  "at the edge of a cliff", "on a lily pad",
];

// ---------------------------------------------------------------------------
// 3. Generation function: combine elements to reach exactly 5000
// ---------------------------------------------------------------------------

function generatePhrases(): string[] {
  const generated: Set<string> = new Set(curatedPhrases);

  // --- Layer 1: "adjective creature" combos ---
  for (const adj of adjectives) {
    for (const creature of creatures) {
      generated.add(`${adj} ${creature}`);
    }
  }

  // --- Layer 2: "creature action" combos ---
  for (const creature of creatures) {
    for (const action of actions) {
      generated.add(`${creature} ${action}`);
    }
  }

  // --- Layer 3: "adjective creature action" combos (selective) ---
  // Pick a strided subset so we don't blow past the limit too quickly
  for (let i = 0; i < adjectives.length; i += 3) {
    for (let j = 0; j < creatures.length; j += 4) {
      for (let k = 0; k < actions.length; k += 5) {
        generated.add(
          `${adjectives[i]} ${creatures[j]} ${actions[k]}`
        );
      }
    }
  }

  // --- Layer 4: "creature action location" combos (selective) ---
  for (let j = 0; j < creatures.length; j += 3) {
    for (let k = 0; k < actions.length; k += 4) {
      for (let l = 0; l < locations.length; l += 5) {
        generated.add(
          `${creatures[j]} ${actions[k]} ${locations[l]}`
        );
      }
    }
  }

  // --- Layer 5: "adjective creature location" combos (selective) ---
  for (let i = 0; i < adjectives.length; i += 4) {
    for (let j = 0; j < creatures.length; j += 5) {
      for (let l = 0; l < locations.length; l += 4) {
        generated.add(
          `${adjectives[i]} ${creatures[j]} ${locations[l]}`
        );
      }
    }
  }

  // Convert to array and trim/pad to exactly 5000
  const result = [...generated];

  // If we somehow have fewer than 5000, generate more with full combos
  if (result.length < 5000) {
    outerLoop:
    for (const adj of adjectives) {
      for (const creature of creatures) {
        for (const action of actions) {
          const phrase = `${adj} ${creature} ${action}`;
          if (!generated.has(phrase)) {
            result.push(phrase);
            generated.add(phrase);
            if (result.length >= 5000) break outerLoop;
          }
        }
      }
    }
  }

  return result.slice(0, 5000);
}

export const complexWords: string[] = generatePhrases();
