export const simpleWords = [
  // Animals - Mammals
  "cat", "dog", "horse", "cow", "pig", "sheep", "goat", "rabbit", "mouse", "rat",
  "hamster", "gerbil", "guinea pig", "squirrel", "chipmunk", "beaver", "otter", "fox", "wolf", "bear",
  "deer", "moose", "elk", "buffalo", "bison", "zebra", "giraffe", "elephant", "rhinoceros", "hippopotamus",
  "lion", "tiger", "leopard", "cheetah", "jaguar", "panther", "cougar", "bobcat", "lynx", "hyena",
  "monkey", "gorilla", "chimpanzee", "orangutan", "baboon", "lemur", "sloth", "armadillo", "porcupine", "hedgehog",
  "bat", "raccoon", "skunk", "badger", "weasel", "ferret", "mink", "mongoose", "meerkat", "koala",
  "kangaroo", "wallaby", "platypus", "opossum", "chinchilla", "camel", "llama", "alpaca", "donkey", "mule",
  "pony", "stallion", "mare", "colt", "puppy", "kitten", "cub", "fawn", "lamb", "calf",
  "whale", "dolphin", "seal", "walrus", "manatee", "narwhal", "porpoise", "gazelle", "antelope", "ibex",
  "yak", "ox", "bull", "ram", "boar", "hog", "piglet", "panda", "polar bear", "grizzly bear",
  "wombat", "dingo", "jackal", "coyote", "reindeer", "caribou", "mammoth", "wolverine", "mole", "shrew",
  "chihuahua", "poodle", "dalmatian", "bulldog", "retriever", "collie", "beagle", "terrier", "husky", "mastiff",
  // Animals - Birds
  "eagle", "hawk", "falcon", "owl", "vulture", "condor", "parrot", "parakeet", "macaw", "cockatoo",
  "robin", "sparrow", "finch", "cardinal", "bluejay", "crow", "raven", "magpie", "starling", "swallow",
  "hummingbird", "woodpecker", "toucan", "pelican", "flamingo", "heron", "crane", "stork", "ibis", "egret",
  "duck", "goose", "swan", "penguin", "ostrich", "emu", "kiwi", "peacock", "turkey", "chicken",
  "rooster", "hen", "chick", "dove", "pigeon", "seagull", "albatross", "puffin", "kingfisher", "canary",
  "oriole", "wren", "lark", "nightingale", "mockingbird", "catbird", "roadrunner", "quail", "pheasant", "grouse",
  "partridge", "ptarmigan", "sandpiper", "plover", "curlew", "avocet", "oystercatcher", "tern", "cormorant", "gannet",
  "osprey", "kestrel", "harrier", "buzzard", "kite", "swift", "martin", "cuckoo", "hoopoe", "bee-eater",
  "hornbill", "mynah", "budgerigar", "lovebird", "cockatiel", "lorikeet", "warbler", "thrush", "nuthatch", "chickadee",
  "goldfinch", "crossbill", "bunting", "tanager", "grosbeak", "siskin", "linnet", "rook", "jackdaw", "jay",
  // Animals - Fish
  "goldfish", "salmon", "trout", "bass", "tuna", "swordfish", "marlin", "shark", "hammerhead", "stingray",
  "manta ray", "clownfish", "angelfish", "pufferfish", "seahorse", "catfish", "carp", "pike", "perch", "cod",
  "herring", "sardine", "anchovy", "mackerel", "barracuda", "piranha", "eel", "moray eel", "flounder", "halibut",
  "sole", "snapper", "grouper", "tilapia", "sturgeon", "paddlefish", "garfish", "blowfish", "lionfish", "zebrafish",
  "betta fish", "guppy", "tetra", "molly", "swordtail", "discus", "arowana", "koi", "sunfish", "bluegill",
  "walleye", "minnow", "goby", "wrasse", "parrotfish", "triggerfish", "boxfish", "flying fish", "lanternfish", "lamprey",
  // Animals - Reptiles & Amphibians
  "snake", "cobra", "python", "viper", "rattlesnake", "boa", "anaconda", "lizard", "gecko", "iguana",
  "chameleon", "komodo dragon", "monitor lizard", "skink", "salamander", "newt", "axolotl", "frog", "toad", "treefrog",
  "bullfrog", "tadpole", "turtle", "tortoise", "sea turtle", "alligator", "crocodile", "caiman", "gavial", "tuatara",
  "horned lizard", "frilled lizard", "basilisk", "anole", "bearded dragon", "blue tongue", "garter snake", "coral snake", "king cobra", "mamba",
  "copperhead", "cottonmouth", "adder", "asp", "sidewinder", "milk snake", "corn snake", "ball python", "tree boa", "water snake",
  "box turtle", "snapping turtle", "painted turtle", "softshell", "terrapin", "glass frog", "poison dart frog", "caecilian", "mudpuppy", "hellbender",
  // Animals - Insects & Bugs
  "butterfly", "moth", "bee", "wasp", "hornet", "ant", "termite", "beetle", "ladybug", "firefly",
  "dragonfly", "damselfly", "grasshopper", "cricket", "locust", "katydid", "mantis", "stick insect", "cockroach", "flea",
  "tick", "louse", "mosquito", "fly", "housefly", "horsefly", "mayfly", "stonefly", "caddisfly", "lacewing",
  "earwig", "silverfish", "centipede", "millipede", "scorpion", "spider", "tarantula", "black widow", "daddy longlegs", "mite",
  "caterpillar", "chrysalis", "cocoon", "larva", "maggot", "grub", "worm", "earthworm", "leech", "slug",
  "snail", "pillbug", "sowbug", "weevil", "aphid", "cicada", "leafhopper", "stink bug", "water strider", "dung beetle",
  "scarab", "june bug", "stag beetle", "rhinoceros beetle", "boll weevil", "bumblebee", "carpenter bee", "yellowjacket", "paper wasp", "mud dauber",
  "walking stick", "assassin bug", "water bug", "bedbug", "lacebug", "sawfly", "gnat", "midge", "crane fly", "robber fly",
  // Animals - Sea Creatures
  "octopus", "squid", "jellyfish", "starfish", "sea urchin", "sea cucumber", "coral", "anemone", "sponge", "crab",
  "lobster", "shrimp", "prawn", "crawfish", "barnacle", "clam", "oyster", "mussel", "scallop", "conch",
  "nautilus", "cuttlefish", "sea slug", "sea lion", "sea otter", "hermit crab", "horseshoe crab", "king crab", "sand dollar", "sea fan",
  "man-of-war", "plankton", "krill", "sea snail", "abalone", "whelk", "limpet", "sea star", "brittle star", "sea dragon",
  "sea snake", "blue whale", "sperm whale", "humpback whale", "orca", "beluga", "dugong", "sea bass", "anglerfish",
  // Food - Fruits
  "apple", "banana", "orange", "grape", "strawberry", "blueberry", "raspberry", "blackberry", "cherry", "peach",
  "pear", "plum", "apricot", "nectarine", "mango", "pineapple", "coconut", "watermelon", "cantaloupe", "honeydew",
  "kiwi fruit", "papaya", "guava", "lychee", "pomegranate", "fig", "date", "passion fruit", "dragon fruit", "star fruit",
  "persimmon", "tangerine", "clementine", "grapefruit", "lime", "lemon", "avocado", "olive", "cranberry", "gooseberry",
  "boysenberry", "elderberry", "mulberry", "currant", "kumquat", "plantain", "jackfruit", "durian", "rambutan", "mangosteen",
  "quince", "loquat", "tamarind", "breadfruit", "soursop", "acai berry", "cactus fruit", "blood orange", "mandarin", "ugli fruit",
  // Food - Vegetables
  "carrot", "potato", "tomato", "onion", "garlic", "broccoli", "cauliflower", "cabbage", "lettuce", "spinach",
  "kale", "celery", "cucumber", "zucchini", "squash", "pumpkin", "eggplant", "pepper", "chili pepper", "bell pepper",
  "corn", "peas", "green bean", "lima bean", "kidney bean", "lentil", "chickpea", "soybean", "edamame", "asparagus",
  "artichoke", "brussels sprout", "beet", "turnip", "radish", "parsnip", "rutabaga", "sweet potato", "yam", "taro",
  "ginger", "turmeric", "leek", "shallot", "scallion", "chive", "watercress", "arugula", "endive", "radicchio",
  "bok choy", "bamboo shoot", "bean sprout", "jicama", "okra", "fennel", "rhubarb", "horseradish", "wasabi", "mushroom",
  // Food - Prepared Foods & Dishes
  "pizza", "hamburger", "hot dog", "sandwich", "taco", "burrito", "quesadilla", "nachos", "enchilada", "tamale",
  "sushi", "ramen", "noodle soup", "fried rice", "spring roll", "dumpling", "wonton", "egg roll", "stir fry", "curry",
  "pasta", "spaghetti", "lasagna", "ravioli", "macaroni", "fettuccine", "gnocchi", "risotto", "polenta", "bruschetta",
  "steak", "roast beef", "pot roast", "meatloaf", "meatball", "pork chop", "fried chicken", "chicken wing", "drumstick", "turkey leg",
  "fish stick", "fish taco", "crab cake", "shrimp cocktail", "lobster roll", "clam chowder", "gumbo", "jambalaya", "paella", "ceviche",
  "salad", "coleslaw", "potato salad", "caesar salad", "soup", "chili", "stew", "casserole", "pot pie", "shepherd's pie",
  "pancake", "waffle", "french toast", "crepe", "omelet", "scrambled eggs", "fried egg", "poached egg", "eggs benedict", "quiche",
  "grilled cheese", "club sandwich", "wrap", "pita", "falafel", "hummus", "guacamole", "salsa", "chips", "french fries",
  "onion ring", "hash brown", "baked potato", "mashed potato", "potato chip", "pretzel", "popcorn", "corn dog", "pulled pork", "ribs",
  "bacon", "sausage", "ham", "jerky", "pepperoni", "salami", "prosciutto", "chorizo", "bratwurst", "kielbasa",
  "tofu", "tempeh", "granola", "oatmeal", "cereal", "porridge", "congee", "dim sum", "satay", "kebab",
  "gyro", "shawarma", "biryani", "tikka masala", "pad thai", "pho", "bibimbap", "teriyaki", "tempura", "tonkatsu",
  // Food - Baked Goods & Desserts
  "bread", "baguette", "croissant", "bagel", "muffin", "scone", "biscuit", "roll", "sourdough", "cornbread",
  "cake", "cupcake", "brownie", "cookie", "pie", "tart", "cheesecake", "tiramisu", "eclair", "cream puff",
  "donut", "cinnamon roll", "danish", "strudel", "baklava", "churro", "cannoli", "macaron", "meringue", "souffle",
  "ice cream", "gelato", "sorbet", "frozen yogurt", "milkshake", "sundae", "popsicle", "ice cream cone", "banana split", "parfait",
  "pudding", "custard", "mousse", "flan", "creme brulee", "panna cotta", "jello", "cobbler", "crumble", "crisp",
  "candy", "chocolate", "fudge", "caramel", "toffee", "taffy", "lollipop", "gummy bear", "licorice", "marshmallow",
  "cotton candy", "candy cane", "jelly bean", "gumdrop", "truffle", "bonbon", "praline", "nougat", "marzipan", "fondant",
  "granola bar", "energy bar", "rice cake", "graham cracker", "shortbread", "gingerbread", "fruitcake", "pound cake", "angel food cake", "bundt cake",
  // Food - Dairy & Cheese
  "milk", "cheese", "butter", "yogurt", "cream", "sour cream", "cottage cheese", "cream cheese", "whipped cream", "ice cream sandwich",
  "cheddar", "mozzarella", "parmesan", "brie", "gouda", "swiss cheese", "blue cheese", "feta", "ricotta", "provolone",
  "kefir", "buttermilk", "condensed milk", "evaporated milk", "powdered milk", "ghee", "custard pie", "cheese wheel",
  // Drinks
  "water", "coffee", "tea", "juice", "soda", "lemonade", "iced tea", "hot chocolate",
  "beer", "wine", "champagne", "cocktail", "martini", "margarita", "mojito", "daiquiri", "sangria", "whiskey",
  "vodka", "rum", "gin", "tequila", "brandy", "bourbon", "sake", "mead", "cider", "ale",
  "espresso", "cappuccino", "latte", "mocha", "americano", "macchiato", "frappe", "cold brew", "matcha", "chai",
  "orange juice", "apple juice", "grape juice", "cranberry juice", "tomato juice", "carrot juice", "coconut water", "almond milk", "oat milk", "soy milk",
  "sparkling water", "tonic water", "ginger ale", "root beer", "energy drink", "sports drink", "punch", "eggnog", "horchata", "kombucha",
  // Household Objects
  "lamp", "lightbulb", "candle", "chandelier", "lantern", "flashlight", "nightlight", "sconce", "torch", "spotlight",
  "clock", "alarm clock", "wall clock", "grandfather clock", "hourglass", "sundial", "stopwatch", "timer", "cuckoo clock", "pocket watch",
  "mirror", "picture frame", "painting", "poster", "calendar", "map", "globe", "sculpture", "vase", "figurine",
  "rug", "carpet", "doormat", "curtain", "blinds", "drape", "tapestry", "tablecloth", "placemat", "coaster",
  "pillow", "cushion", "blanket", "comforter", "quilt", "duvet", "sheet", "mattress", "sleeping bag", "hammock",
  "broom", "mop", "dustpan", "vacuum cleaner", "feather duster", "bucket", "spray bottle", "trash can", "recycling bin",
  "iron", "ironing board", "clothespin", "clothesline", "laundry basket", "hamper", "washing machine", "dryer", "hanger", "lint roller",
  "door", "doorknob", "doorbell", "door knocker", "keyhole", "deadbolt", "padlock", "key", "key ring", "lock",
  "window", "windowsill", "window screen", "shutter", "skylight", "stained glass", "venetian blind", "roller shade", "awning",
  "stairs", "staircase", "railing", "banister", "step stool", "ladder", "step ladder", "escalator", "elevator", "ramp",
  "fan", "ceiling fan", "desk fan", "space heater", "radiator", "thermostat", "air conditioner", "humidifier", "dehumidifier", "air purifier",
  "smoke detector", "fire extinguisher", "fire alarm", "security camera", "doorbell camera", "motion sensor", "surge protector", "power strip", "extension cord",
  "light switch", "outlet", "plug", "fuse box", "circuit breaker", "dimmer switch", "lava lamp", "desk lamp", "floor lamp",
  "ashtray", "incense", "potpourri", "air freshener", "diffuser", "fly swatter", "mousetrap", "ant trap", "bug zapper",
  "umbrella stand", "coat rack", "hat rack", "shoe rack", "magazine rack", "wine rack", "spice rack", "towel rack", "pot rack", "drying rack",
  "welcome mat", "bath mat", "area rug", "throw rug", "yoga mat", "exercise mat", "play mat",
  "fire poker", "fireplace screen", "firewood", "kindling", "matches", "lighter", "candle holder", "candlestick", "menorah", "oil lamp",
  "bookend", "paperweight", "snow globe", "music box", "jewelry box", "trinket box", "keepsake box", "treasure chest", "piggy bank", "coin jar",
  "plant pot", "flower pot", "window box", "terrarium", "aquarium", "fish tank", "bird cage", "pet bed", "dog bowl", "cat tree",
  "wind chime", "bird feeder", "bird bath", "garden gnome", "scarecrow", "weathervane",
  "plunger", "toilet brush", "dish rack", "cutting board", "corkscrew", "bottle opener", "can opener", "nutcracker", "garlic press", "peeler",
  "whisk", "spatula", "ladle", "tongs", "rolling pin", "colander", "strainer", "grater", "sieve", "funnel",
  "thermos", "water bottle", "sippy cup", "straw", "trivet", "hot pad", "oven mitt", "apron", "chef hat",
  "napkin", "napkin ring", "centerpiece", "fruit bowl", "bread basket", "serving tray", "cake stand", "gravy boat", "butter dish",
  "salt shaker", "pepper mill", "sugar bowl", "creamer", "teapot", "tea kettle", "coffee pot", "french press", "coffee grinder", "espresso machine",
  "toaster", "blender", "mixer", "food processor", "microwave", "slow cooker", "pressure cooker", "rice cooker", "waffle iron", "griddle",
  "stove", "oven", "refrigerator", "freezer", "dishwasher", "garbage disposal", "trash compactor", "ice maker", "water filter", "range hood",
  "frying pan", "saucepan", "stock pot", "dutch oven", "wok", "skillet", "baking sheet", "muffin tin", "cake pan", "pie dish",
  "plate", "bowl", "cup", "mug", "glass", "goblet", "wine glass", "champagne flute", "shot glass", "tumbler",
  "fork", "knife", "spoon", "chopsticks", "steak knife", "butter knife", "soup spoon", "dessert fork", "salad fork", "serving spoon",
  // Furniture
  "chair", "table", "desk", "sofa", "couch", "loveseat", "recliner", "rocking chair", "armchair", "bean bag",
  "stool", "bar stool", "bench", "ottoman", "futon", "daybed", "chaise lounge", "papasan chair", "folding chair", "high chair",
  "bed", "bunk bed", "canopy bed", "waterbed", "crib", "cradle", "bassinet", "trundle bed", "murphy bed", "loft bed",
  "dresser", "wardrobe", "armoire", "chest of drawers", "nightstand", "vanity", "hope chest", "cedar chest", "trunk", "hutch",
  "bookshelf", "bookcase", "shelf", "floating shelf", "corner shelf", "display case", "curio cabinet", "china cabinet", "buffet", "sideboard",
  "dining table", "kitchen table", "coffee table", "end table", "side table", "console table", "folding table", "card table", "picnic table", "patio table",
  "filing cabinet", "desk chair", "office chair", "swivel chair", "computer desk", "standing desk", "cubicle", "lectern", "podium", "reception desk",
  "tv stand", "entertainment center", "media console", "fireplace mantel", "hearth", "room divider", "folding screen", "partition",
  "porch swing", "glider", "adirondack chair", "lawn chair", "deck chair", "lounge chair", "beach chair", "camping chair", "director chair", "throne",
  "cot", "air mattress", "foam mattress", "box spring", "headboard", "footboard", "bed frame", "bed rail", "canopy", "mosquito net",
  "workbench", "sawhorse", "easel", "music stand", "coat stand", "plant stand",
  "bar cart", "kitchen island", "breakfast bar", "kitchen cabinet", "pantry shelf", "lazy susan", "spice cabinet", "wine cabinet", "linen closet", "storage bench",
  "toy chest", "toy box", "playpen", "changing table", "booster seat", "footstool", "hassock", "pouf", "floor cushion",
  "wall shelf", "pegboard", "corkboard", "whiteboard", "chalkboard", "bulletin board", "memo board",
  "shoe bench", "mudroom bench", "garden bench", "park bench", "piano bench", "vanity stool", "dressing table", "jewelry armoire",
  // Clothing & Accessories
  "shirt", "t-shirt", "polo shirt", "dress shirt", "blouse", "tank top", "camisole", "tube top", "crop top", "halter top",
  "sweater", "cardigan", "pullover", "hoodie", "sweatshirt", "fleece", "vest", "turtleneck", "henley", "jersey",
  "jacket", "coat", "blazer", "suit jacket", "sport coat", "parka", "windbreaker", "raincoat", "trench coat", "overcoat",
  "pants", "jeans", "shorts", "skirt", "dress", "gown", "jumpsuit", "romper", "overalls", "leggings",
  "underwear", "boxers", "briefs", "bra", "undershirt", "slip", "nightgown", "pajamas", "bathrobe", "kimono",
  "socks", "stockings", "tights", "pantyhose", "leg warmers", "knee socks", "ankle socks", "tube socks", "compression socks", "toe socks",
  "shoe", "boot", "sneaker", "sandal", "flip flop", "slipper", "heel", "loafer", "moccasin", "oxford shoe",
  "cowboy boot", "hiking boot", "rain boot", "snow boot", "work boot", "combat boot", "ankle boot", "riding boot", "wellington boot", "galosh",
  "hat", "cap", "baseball cap", "beanie", "beret", "fedora", "top hat", "cowboy hat", "sun hat", "visor",
  "headband", "bandana", "turban", "hijab", "veil", "tiara", "crown", "headpiece", "hair clip", "hair bow",
  "scarf", "shawl", "stole", "poncho", "cape", "necktie", "bow tie", "ascot", "cravat",
  "belt", "suspenders", "garter", "cummerbund", "sash", "waistband", "buckle", "clasp", "zipper", "button",
  "gloves", "mittens", "muff", "arm warmers", "wristband", "sweatband", "elbow pad", "knee pad", "shin guard", "shoulder pad",
  "sunglasses", "eyeglasses", "monocle", "goggles", "ski goggles", "safety glasses", "reading glasses", "contact lens", "eye patch", "blindfold",
  "purse", "handbag", "clutch", "tote bag", "messenger bag", "backpack", "fanny pack", "duffel bag", "garment bag", "suitcase",
  "wallet", "coin purse", "money clip", "passport holder", "luggage tag", "keychain", "lanyard", "badge", "name tag", "pin",
  "lab coat", "wetsuit", "swimsuit", "bikini", "swim trunks", "life jacket",
  "uniform", "scrubs", "coveralls", "flight suit", "space suit", "tuxedo", "evening gown", "wedding dress", "prom dress", "cocktail dress",
  "tutu", "leotard", "unitard", "bodysuit", "onesie", "snowsuit", "ski jacket", "ski pants", "snow pants",
  "cleat", "ballet shoe", "tap shoe", "bowling shoe", "golf shoe", "tennis shoe", "running shoe", "climbing shoe", "water shoe",
  // Nature - Plants, Trees, Flowers, Landscapes
  "tree", "oak tree", "maple tree", "pine tree", "palm tree", "willow tree", "birch tree", "cedar tree", "elm tree", "ash tree",
  "redwood", "sequoia", "cypress", "spruce", "fir tree", "hemlock", "juniper", "magnolia", "dogwood", "cherry blossom",
  "apple tree", "orange tree", "lemon tree", "peach tree", "pear tree", "plum tree", "fig tree", "olive tree", "walnut tree", "chestnut tree",
  "coconut palm", "date palm", "banana tree", "bamboo", "eucalyptus", "baobab", "acacia", "mahogany", "teak", "ebony",
  "flower", "rose", "daisy", "sunflower", "tulip", "lily", "orchid", "daffodil", "carnation", "chrysanthemum",
  "peony", "hydrangea", "lavender", "jasmine", "gardenia", "hibiscus", "marigold", "pansy", "petunia", "begonia",
  "geranium", "azalea", "rhododendron", "camellia", "wisteria", "bougainvillea", "clematis", "morning glory", "honeysuckle", "foxglove",
  "snapdragon", "zinnia", "dahlia", "aster", "cosmos", "poppy", "iris", "crocus", "hyacinth", "freesia",
  "lilac", "violet", "bluebell", "buttercup", "clover", "dandelion", "thistle", "goldenrod", "black-eyed susan", "coneflower",
  "lotus", "water lily", "cattail", "bulrush", "reed", "papyrus", "marsh grass", "moss", "lichen", "fern",
  "ivy", "vine", "creeper", "tendril", "hedge", "shrub", "bush", "bramble", "thicket", "undergrowth",
  "grass", "lawn", "meadow", "prairie", "field", "pasture", "hay", "wheat", "barley",
  "oat", "rye", "rice paddy", "corn stalk", "sugarcane", "cotton plant", "tobacco plant", "tea plant", "coffee plant", "cocoa tree",
  "cactus", "succulent", "aloe vera", "agave", "yucca", "prickly pear", "barrel cactus", "saguaro", "tumbleweed", "desert rose",
  "toadstool", "chanterelle", "portobello", "shiitake", "oyster mushroom", "morel", "puffball", "bracket fungus",
  "seaweed", "kelp", "algae", "sea grass", "duckweed", "water hyacinth", "lily pad", "pond weed", "water lettuce", "water fern",
  "herb", "basil", "oregano", "thyme", "rosemary", "sage", "mint", "parsley", "cilantro", "dill",
  "mountain", "volcano", "hill", "valley", "canyon", "cliff", "ravine", "gorge", "mesa", "plateau",
  "river", "stream", "creek", "brook", "waterfall", "rapids", "delta", "estuary", "tributary", "fjord",
  "lake", "pond", "lagoon", "reservoir", "marsh", "swamp", "bog", "wetland", "oasis", "spring",
  "ocean", "sea", "bay", "gulf", "strait", "channel", "cove", "inlet", "harbor", "reef",
  "island", "peninsula", "archipelago", "atoll", "sandbar", "shoal", "isthmus", "continent", "coastline",
  "beach", "shore", "dune", "sand", "pebble", "boulder", "rock", "stone", "gravel", "cobblestone",
  "cave", "cavern", "grotto", "stalactite", "stalagmite", "sinkhole", "tunnel", "mine shaft", "quarry", "crater",
  "forest", "jungle", "rainforest", "woodland", "grove", "orchard", "clearing", "glade",
  "desert", "savanna", "tundra", "glacier", "iceberg", "ice cap", "permafrost", "snowfield", "avalanche", "landslide",
  "geyser", "hot spring", "mudflat", "tide pool", "mangrove", "coral reef", "kelp forest", "sea floor", "trench", "abyss",
  "aurora", "sunset", "sunrise", "horizon", "skyline", "constellation", "milky way", "nebula", "shooting star",
  // Weather & Sky
  "sun", "moon", "star", "cloud", "rain", "snow", "hail", "sleet", "fog", "mist",
  "thunder", "lightning", "tornado", "hurricane", "cyclone", "typhoon", "blizzard", "sandstorm", "dust devil", "waterspout",
  "rainbow", "halo", "sundog", "mirage", "frost", "dew", "icicle", "snowflake", "raindrop", "puddle",
  "wind", "breeze", "gust", "gale", "storm", "tempest", "squall", "drizzle", "downpour", "shower",
  "cumulus cloud", "thunderhead", "cirrus cloud", "stratus cloud", "fog bank", "smog", "haze", "overcast",
  "full moon", "crescent moon", "half moon", "new moon", "eclipse", "lunar eclipse", "solar eclipse", "meteor", "comet", "asteroid",
  "north star", "big dipper", "little dipper", "orion", "venus", "mars", "jupiter", "saturn", "mercury", "neptune",
  "satellite", "space station", "rocket ship", "ufo", "flying saucer", "planet", "rings of saturn", "moon crater", "sunspot", "solar flare",
  "thermometer", "barometer", "anemometer", "rain gauge", "hygrometer", "weather balloon", "doppler radar", "wind sock", "weather map",
  "snow shovel", "ice scraper", "snow plow", "salt truck", "lightning rod", "wind turbine",
  // Body Parts
  "head", "face", "forehead", "temple", "cheek", "chin", "jaw", "skull", "brain", "scalp",
  "eye", "eyebrow", "eyelash", "eyelid", "pupil", "retina", "cornea", "tear duct", "eye socket",
  "ear", "earlobe", "ear canal", "eardrum", "nose", "nostril", "nasal bridge", "mouth", "lip", "tongue",
  "tooth", "molar", "canine tooth", "wisdom tooth", "gum", "palate", "uvula", "tonsil", "throat", "adam's apple",
  "neck", "shoulder", "arm", "elbow", "forearm", "wrist", "hand", "palm", "finger", "thumb",
  "fingernail", "knuckle", "fist", "index finger", "pinky finger", "ring finger", "middle finger", "cuticle", "fingerprint",
  "chest", "breast", "rib", "ribcage", "sternum", "collarbone", "shoulder blade", "spine", "backbone", "vertebra",
  "stomach", "belly", "navel", "waist", "hip", "pelvis", "thigh", "leg",
  "knee", "kneecap", "shin", "ankle", "foot", "toe", "toenail",
  "arch", "instep", "achilles tendon", "hamstring", "bicep", "tricep", "muscle", "bone", "joint", "tendon",
  // Vehicles & Transportation
  "car", "truck", "van", "bus", "taxi", "limousine", "ambulance", "fire truck", "police car", "tow truck",
  "pickup truck", "dump truck", "garbage truck", "cement mixer", "tanker truck", "flatbed truck", "moving van", "ice cream truck", "food truck", "mail truck",
  "motorcycle", "scooter", "moped", "dirt bike", "chopper", "sidecar", "trike", "quad bike", "snowmobile", "jet ski",
  "bicycle", "tricycle", "unicycle", "tandem bicycle", "mountain bike", "road bike", "bmx bike", "recumbent bike", "penny farthing", "rickshaw",
  "skateboard", "longboard", "roller skates", "inline skates", "hoverboard", "segway", "electric scooter", "wagon", "wheelbarrow",
  "train", "locomotive", "caboose", "boxcar", "freight train", "passenger train", "subway", "monorail", "trolley", "cable car",
  "airplane", "helicopter", "blimp", "hot air balloon", "hang glider", "parachute", "jet", "biplane", "seaplane",
  "rocket", "space shuttle", "spacecraft", "drone", "paraglider", "ultralight", "zeppelin", "propeller plane", "fighter jet",
  "boat", "ship", "sailboat", "yacht", "canoe", "kayak", "raft", "rowboat", "speedboat", "tugboat",
  "ferry", "cruise ship", "submarine", "aircraft carrier", "battleship", "destroyer", "frigate", "houseboat", "pontoon boat", "catamaran",
  "surfboard", "paddleboard", "windsurfer", "water ski", "inner tube", "life raft", "dinghy", "gondola", "barge", "tanker",
  "sled", "toboggan", "bobsled", "dogsled", "sleigh", "ski lift", "gondola lift", "chairlift", "tram", "funicular",
  "horse cart", "stagecoach", "chariot", "covered wagon", "buggy", "carriage", "pedicab", "sedan chair",
  "forklift", "bulldozer", "excavator", "backhoe", "steamroller", "tractor", "combine harvester", "plow", "hay baler",
  "golf cart", "go kart", "bumper car", "dune buggy", "monster truck", "race car", "stock car", "dragster", "formula one car", "rally car",
  // Buildings & Structures
  "house", "apartment", "cabin", "cottage", "mansion", "palace", "castle", "fortress", "chateau", "villa",
  "igloo", "tepee", "yurt", "hut", "shack", "bungalow", "duplex", "townhouse", "penthouse", "condo",
  "skyscraper", "tower", "high rise", "office building", "warehouse", "factory", "mill", "refinery", "power plant",
  "church", "cathedral", "chapel", "mosque", "synagogue", "pagoda", "shrine", "monastery", "abbey",
  "school", "university", "library", "museum", "gallery", "theater", "cinema", "opera house", "concert hall", "auditorium",
  "hospital", "clinic", "pharmacy", "dentist office", "veterinary clinic", "nursing home", "hospice", "asylum", "sanatorium", "infirmary",
  "store", "shop", "mall", "market", "bazaar", "boutique", "supermarket", "grocery store", "bakery", "butcher shop",
  "restaurant", "cafe", "diner", "pub", "bar", "tavern", "nightclub", "bistro", "pizzeria", "food court",
  "hotel", "motel", "inn", "hostel", "resort", "lodge", "bed and breakfast", "campground", "trailer park", "vacation home",
  "bank", "post office", "courthouse", "city hall", "capitol building", "embassy", "consulate", "parliament", "white house", "pentagon",
  "prison", "jail", "police station", "fire station", "military base", "barracks", "bunker", "guard tower", "watchtower", "lookout tower",
  "bridge", "overpass", "underpass", "aqueduct", "dam", "levee", "pier", "dock", "wharf",
  "lighthouse", "windmill", "water tower", "clock tower", "bell tower", "minaret", "steeple", "spire", "dome", "cupola",
  "barn", "silo", "stable", "corral", "chicken coop", "doghouse", "greenhouse", "shed", "garage", "carport",
  "stadium", "arena", "colosseum", "amphitheater", "gymnasium", "swimming pool", "ice rink", "bowling alley", "tennis court", "basketball court",
  "airport", "train station", "bus station", "subway station", "marina", "helipad", "runway", "control tower", "hangar",
  "fountain", "statue", "monument", "obelisk", "column", "pillar", "pyramid", "sphinx", "totem pole",
  "fence", "gate", "wall", "guardrail", "barricade", "bollard", "turnstile", "drawbridge",
  "chimney", "smokestack", "antenna", "flagpole", "billboard", "signpost", "street sign", "traffic light", "street lamp", "fire hydrant",
  "gazebo", "pergola", "pavilion", "bandstand", "kiosk", "booth", "tent", "marquee",
  // Tools & Hardware
  "hammer", "screwdriver", "wrench", "pliers", "saw", "drill", "level", "tape measure", "ruler", "square",
  "nail", "screw", "bolt", "nut", "washer", "rivet", "staple", "tack", "brad",
  "handsaw", "hacksaw", "circular saw", "jigsaw", "band saw", "table saw", "chainsaw", "miter saw", "coping saw", "scroll saw",
  "chisel", "plane", "rasp", "file", "sandpaper", "sanding block", "grinder", "polisher", "buffer", "router",
  "axe", "hatchet", "maul", "sledgehammer", "pickaxe", "mattock", "crowbar", "pry bar", "wrecking bar", "nail puller",
  "clamp", "vise", "vice grip", "locking pliers", "needle nose pliers", "channel lock", "wire cutter", "wire stripper", "crimper", "soldering iron",
  "socket wrench", "allen wrench", "pipe wrench", "torque wrench", "adjustable wrench", "box wrench", "open end wrench", "ratchet", "socket set", "impact driver",
  "shovel", "spade", "rake", "hoe", "pitchfork", "trowel", "garden fork", "pruner", "hedge trimmer", "lawn mower",
  "garden hose", "sprinkler", "watering can", "rain barrel", "compost bin", "leaf blower", "weed whacker", "edger", "post hole digger",
  "paintbrush", "paint roller", "paint tray", "paint bucket", "putty knife", "scraper", "caulk gun", "spray gun", "airbrush", "stencil",
  "scaffolding", "jack", "car jack", "hydraulic jack", "bottle jack", "scissor jack", "jack stand", "dolly",
  "toolbox", "tool belt", "tool chest", "utility knife", "box cutter", "razor blade", "scissors", "shears",
  "welding torch", "welding mask", "blowtorch", "heat gun", "glue gun", "staple gun", "nail gun", "rivet gun", "grease gun",
  "multimeter", "voltage tester", "stud finder", "wire gauge", "caliper", "micrometer", "protractor", "compass", "plumb bob", "chalk line",
  "bench grinder", "belt sander", "orbital sander", "power drill", "hammer drill", "rotary tool", "oscillating tool", "reciprocating saw", "angle grinder", "die grinder",
  "pipe cutter", "tube bender", "flaring tool", "tap and die", "thread gauge", "deburring tool", "reamer", "countersink", "drill bit", "hole saw",
  "bracket", "hinge", "latch", "hasp", "hook", "eye bolt", "turnbuckle", "shackle", "carabiner",
  "rope", "chain", "cable", "wire", "twine", "cord", "bungee cord", "zip tie", "duct tape", "electrical tape",
  "steel wool", "wire brush", "bristle brush", "dust brush", "shop vac", "air compressor", "pressure washer", "generator", "welder",
  "bench vise", "anvil", "forge", "bellows", "quenching tank", "grinding wheel", "whetstone",
  // Musical Instruments
  "guitar", "bass guitar", "electric guitar", "acoustic guitar", "ukulele", "banjo", "mandolin", "sitar", "lute", "harp",
  "violin", "viola", "cello", "double bass", "fiddle", "zither", "dulcimer", "balalaika", "bouzouki", "erhu",
  "piano", "keyboard", "organ", "harpsichord", "accordion", "concertina", "melodica", "synthesizer", "keytar", "celesta",
  "drum", "snare drum", "bass drum", "tom tom", "bongo", "conga", "djembe", "timpani", "tambourine", "cymbal",
  "xylophone", "marimba", "vibraphone", "glockenspiel", "steel drum", "hand drum", "cajon", "cowbell", "triangle", "gong",
  "flute", "piccolo", "clarinet", "oboe", "bassoon", "recorder", "fife", "pan flute", "ocarina", "harmonica",
  "trumpet", "trombone", "french horn", "tuba", "cornet", "bugle", "flugelhorn", "sousaphone", "euphonium", "didgeridoo",
  "saxophone", "bagpipe", "kazoo", "slide whistle", "vuvuzela", "whistle", "jaw harp", "kalimba", "turntable",
  // Sports & Games
  "baseball", "basketball", "football", "soccer ball", "tennis ball", "golf ball", "volleyball", "bowling ball", "rugby ball", "cricket ball",
  "baseball bat", "tennis racket", "golf club", "hockey stick", "lacrosse stick", "badminton racket", "ping pong paddle", "cricket bat", "polo mallet", "field hockey stick",
  "baseball glove", "boxing glove", "goalkeeper glove", "batting helmet", "football helmet", "hockey helmet", "ski helmet", "bike helmet", "riding helmet", "fencing mask",
  "basketball hoop", "soccer goal", "football goalpost", "tennis net", "volleyball net", "badminton net", "hockey net", "ping pong table", "pool table", "foosball table",
  "dartboard", "dart", "archery target", "bullseye", "scoreboard", "referee", "trophy", "medal",
  "chess board", "chess piece", "checkerboard", "backgammon", "dominoes", "dice", "playing cards", "poker chip", "roulette wheel", "slot machine",
  "snowboard", "wakeboard", "kiteboard", "bodyboard", "skimboard",
  "ski", "ski pole", "ski boot", "snowshoe", "ice skate", "roller skate", "inline skate", "figure skate", "hockey skate", "speed skate",
  "fishing rod", "fishing reel", "fishing hook", "fishing net", "tackle box", "lure", "bobber", "fly rod", "fishing line", "sinker",
  "boxing ring", "punching bag", "speed bag", "jump rope", "resistance band", "dumbbell", "barbell", "kettlebell", "weight bench", "treadmill",
  "exercise bike", "elliptical", "rowing machine", "pull up bar", "medicine ball", "yoga ball", "foam roller", "balance beam", "parallel bars", "pommel horse",
  "trampoline", "diving board", "swim goggles", "swim cap", "snorkel", "scuba tank", "flipper", "kickboard",
  "climbing rope", "harness", "crampon", "ice axe", "piton", "chalk bag",
  "horseshoe", "frisbee", "boomerang", "yo-yo", "hula hoop", "pogo stick", "stilts", "slingshot", "catapult",
  "croquet mallet", "bocce ball", "shuffleboard", "cornhole board", "tetherball", "hopscotch", "dodgeball",
  // Professions & People
  "doctor", "nurse", "surgeon", "dentist", "pharmacist", "paramedic", "veterinarian", "therapist", "optometrist", "radiologist",
  "teacher", "professor", "principal", "tutor", "librarian", "counselor", "dean", "superintendent", "coach", "instructor",
  "chef", "cook", "baker", "butcher", "waiter", "waitress", "bartender", "barista", "sommelier", "caterer",
  "firefighter", "police officer", "detective", "sheriff", "marshal", "ranger", "lifeguard", "security guard", "bodyguard", "bouncer",
  "soldier", "sailor", "marine", "pilot", "navigator", "captain", "admiral", "general", "sergeant", "corporal",
  "farmer", "rancher", "fisherman", "lumberjack", "miner", "cowboy", "shepherd", "beekeeper", "gardener", "florist",
  "carpenter", "plumber", "electrician", "mechanic", "mason", "roofer", "glazier", "locksmith",
  "lawyer", "judge", "paralegal", "notary", "bailiff", "prosecutor", "attorney", "solicitor", "barrister", "magistrate",
  "artist", "sculptor", "photographer", "filmmaker", "animator", "illustrator", "graphic designer", "architect", "interior designer",
  "musician", "singer", "drummer", "guitarist", "pianist", "violinist", "conductor", "composer", "disc jockey", "sound engineer",
  "actor", "actress", "director", "producer", "screenwriter", "stunt double", "choreographer", "dancer", "ballerina", "mime",
  "writer", "author", "journalist", "reporter", "editor", "publisher", "blogger", "poet", "novelist", "columnist",
  "scientist", "chemist", "physicist", "biologist", "geologist", "astronomer", "archaeologist", "anthropologist", "meteorologist", "botanist",
  "engineer", "programmer", "developer", "data scientist", "web designer", "game designer", "roboticist", "inventor",
  "businessman", "accountant", "banker", "broker", "trader", "economist", "consultant", "manager", "executive", "entrepreneur",
  "salesperson", "realtor", "auctioneer", "cashier", "clerk", "receptionist", "secretary", "assistant", "intern", "volunteer",
  "truck driver", "bus driver", "taxi driver", "delivery driver", "chauffeur", "train conductor", "flight attendant", "air traffic controller", "ship captain",
  "clown", "magician", "juggler", "acrobat", "trapeze artist", "ringmaster", "fortune teller", "street performer", "ventriloquist", "puppeteer",
  "king", "queen", "prince", "princess", "knight", "jester", "wizard", "witch", "pirate", "ninja",
  "astronaut", "diver", "explorer", "mountaineer", "spelunker", "paleontologist", "zoologist", "marine biologist", "ecologist",
  "monk", "nun", "priest", "bishop", "pope", "rabbi", "imam", "shaman", "druid",
  "baby", "toddler", "child", "teenager", "adult", "bride", "groom", "grandmother", "grandfather",
  "cheerleader", "mascot", "umpire", "announcer", "commentator",
  "superhero", "villain", "sidekick", "spy", "samurai", "gladiator", "viking", "pharaoh", "emperor", "sultan",
  "snowman", "mummy", "zombie", "vampire", "werewolf", "ghost", "skeleton", "robot", "alien",
  // Technology & Electronics
  "computer", "laptop", "desktop", "tablet", "smartphone", "cell phone", "flip phone", "smartwatch", "fitness tracker", "pager",
  "monitor", "screen", "display", "projector", "touchscreen", "lcd screen", "led screen",
  "mouse pad", "joystick", "game controller", "steering wheel", "flight stick", "trackball", "stylus", "graphics tablet",
  "printer", "scanner", "copier", "fax machine", "shredder", "laminator", "label maker", "paper cutter", "hole punch",
  "camera", "video camera", "webcam", "dash cam", "action camera", "film camera", "polaroid", "disposable camera", "camera lens",
  "television", "remote control", "cable box", "dvd player", "blu-ray player", "vcr", "streaming stick",
  "speaker", "headphones", "earbuds", "microphone", "amplifier", "subwoofer", "soundbar", "record player", "cassette player",
  "radio", "walkie talkie", "cb radio", "ham radio", "transistor radio", "boombox", "stereo", "receiver", "equalizer",
  "battery", "charger", "power bank", "solar panel", "transformer", "inverter", "power supply",
  "usb drive", "hard drive", "ssd", "memory card", "cd", "dvd", "floppy disk", "flash drive", "external hard drive",
  "modem", "switch", "hub", "access point", "ethernet cable", "fiber optic cable", "coaxial cable", "hdmi cable", "usb cable",
  "server", "rack", "mainframe", "supercomputer", "raspberry pi", "arduino", "circuit board", "motherboard", "graphics card",
  "chip", "processor", "ram stick", "heat sink", "cooling fan", "power cord", "adapter", "dongle", "splitter", "converter",
  "calculator", "cash register", "barcode scanner", "atm", "vending machine", "jukebox", "arcade machine", "pinball machine", "claw machine",
  "gps device", "radar detector", "metal detector", "geiger counter", "oscilloscope",
  "robotic arm", "3d printer", "cnc machine", "laser cutter", "soldering station",
  "vr headset", "ar glasses", "smart speaker", "smart thermostat", "smart lock", "smart plug", "smart bulb", "smart doorbell",
  "telescope", "microscope", "binoculars", "magnifying glass", "periscope", "night vision goggles", "thermal camera", "x-ray machine", "mri machine",
  "ring light", "studio light", "strobe light", "laser pointer", "led strip", "neon sign", "digital clock",
  "smoke machine", "fog machine", "bubble machine", "snow machine", "popcorn machine", "cotton candy machine", "bread maker",
  // Kitchen Items
  "measuring cup", "measuring spoon", "mixing bowl", "salad bowl", "soup bowl", "cereal bowl", "rice bowl", "ramekin", "souffle dish", "casserole dish",
  "cookie sheet", "baking pan", "bundt pan", "springform pan", "loaf pan", "pizza stone", "pizza peel", "pizza cutter", "pastry brush", "pastry bag",
  "cookie cutter", "biscuit cutter", "melon baller", "apple corer", "cherry pitter", "egg slicer", "mandoline", "spiralizer", "juicer", "citrus reamer",
  "meat thermometer", "candy thermometer", "kitchen scale", "kitchen timer", "egg timer", "oven thermometer",
  "ice cube tray", "popsicle mold", "candy mold", "chocolate mold", "silicone mold", "gelatin mold", "ice cream scoop",
  "cheese grater", "zester", "microplane", "box grater", "rotary grater", "potato masher", "potato ricer", "food mill", "mortar and pestle",
  "wine opener", "bottle stopper", "wine aerator", "decanter", "carafe", "pitcher", "water pitcher", "punch bowl",
  "tea infuser", "tea strainer", "coffee filter", "pour over", "aeropress", "moka pot", "percolator", "cold brew maker", "milk frother", "tea ball",
  "dish towel", "dish cloth", "scrub brush", "dish sponge", "utensil holder", "knife block",
  "pepper grinder", "salt cellar", "oil cruet", "condiment tray",
  "wax paper", "parchment paper", "aluminum foil", "plastic wrap", "freezer bag", "sandwich bag", "vacuum sealer", "food storage container", "mason jar", "canning jar",
  "paper towel holder", "napkin holder", "toothpick holder", "straw dispenser", "soap dispenser", "sponge holder", "sink strainer", "drain plug",
  "bread knife", "carving knife", "cleaver", "paring knife", "chef knife", "santoku knife", "fillet knife", "boning knife",
  "vegetable peeler", "julienne peeler", "garlic crusher", "ginger grater", "avocado slicer",
  "egg cup", "egg poacher", "egg ring", "omelet pan", "crepe pan", "pancake griddle", "waffle maker", "donut maker", "sandwich press", "panini press",
  // Toys & Games
  "doll", "teddy bear", "action figure", "toy soldier", "toy car", "toy truck", "toy train", "toy airplane", "toy boat", "toy robot",
  "building blocks", "lego", "lincoln logs", "tinker toys", "erector set", "model kit", "puzzle", "jigsaw puzzle", "rubik's cube", "tangram",
  "board game", "card game", "video game", "air hockey",
  "spinning top", "slinky",
  "water gun", "nerf gun", "cap gun", "paintball gun", "laser tag", "toy sword", "toy shield", "toy crown", "toy wand",
  "puppet", "hand puppet", "finger puppet", "marionette", "ventriloquist dummy", "sock puppet", "paper doll", "paper airplane", "origami crane", "paper boat",
  "balloon", "bubble wand", "kaleidoscope", "viewmaster", "magic eight ball", "jack in the box", "wind up toy", "pull toy", "push toy",
  "rattle", "teething ring", "pacifier", "mobile", "ball pit", "bouncy house", "swing set", "slide", "jungle gym",
  "sandbox", "sand castle", "bucket and shovel", "beach ball", "pool float", "pool noodle", "inflatable pool", "kiddie pool", "water slide",
  "balance bike", "training wheels", "roller coaster", "merry-go-round", "ferris wheel", "carousel",
  // School & Office Supplies
  "pencil", "pen", "marker", "crayon", "colored pencil", "highlighter", "chalk", "dry erase marker", "fountain pen", "quill",
  "eraser", "pencil sharpener", "pencil case", "pen holder", "ink bottle", "ink cartridge", "blotter", "correction tape", "white out",
  "notebook", "binder", "folder", "portfolio", "planner", "journal", "diary", "ledger", "composition book", "spiral notebook",
  "paper", "lined paper", "graph paper", "construction paper", "cardstock", "tissue paper", "carbon paper", "tracing paper", "origami paper", "crepe paper",
  "t-square", "french curve", "template", "grid",
  "tape", "glue", "glue stick", "paste", "rubber cement", "epoxy", "super glue", "hot glue", "double sided tape",
  "paper clip", "binder clip", "push pin", "thumbtack", "rubber band", "fastener", "grommet", "eyelet", "brad fastener",
  "abacus", "slide rule", "atlas", "encyclopedia", "dictionary", "textbook", "workbook", "flash card",
  "book bag", "pencil pouch", "lunch box", "lunch bag", "id badge",
  "desk organizer", "inbox tray", "outbox tray", "file folder", "hanging folder", "label", "index card", "divider tab", "sheet protector",
  "dry erase board", "easel pad", "flip chart", "poster board", "presentation board", "trifold board",
  "stamp", "stamp pad", "ink pad", "wax seal", "embosser", "letter opener", "mail sorter", "envelope", "postcard", "letterhead",
  "clipboard", "name plate", "desk calendar", "wall calendar", "day planner", "sticky note", "memo pad", "legal pad", "scratch pad", "post-it note",
  "bookmark", "page flag", "reading light", "book stand", "document holder", "copy stand", "monitor stand", "laptop stand",
  "typewriter", "adding machine", "receipt book", "business card", "rolodex", "address book", "phone book",
  // Bathroom Items
  "bathtub", "shower head", "faucet", "sink", "toilet", "bidet", "urinal", "drain", "stopper",
  "towel", "bath towel", "hand towel", "washcloth", "loofah", "bath brush", "back scrubber", "pumice stone", "bath bomb",
  "soap", "soap dish", "shampoo", "conditioner", "body wash", "bubble bath", "bath salt", "shower gel", "face wash",
  "toothbrush", "toothpaste", "dental floss", "mouthwash", "tongue scraper", "water pick", "electric toothbrush", "toothbrush holder", "dentures", "retainer",
  "razor", "shaving cream", "aftershave", "electric razor", "straight razor", "shaving brush", "tweezers", "nail clipper",
  "hair dryer", "curling iron", "flat iron", "hair brush", "comb", "hair pick", "hair roller", "bobby pin", "hair tie", "scrunchie",
  "vanity mirror", "magnifying mirror", "medicine cabinet", "bathroom scale", "toilet paper", "tissue box", "cotton ball", "cotton swab",
  "deodorant", "perfume", "cologne", "lotion", "sunscreen", "moisturizer", "lip balm", "makeup", "mascara", "lipstick",
  // Garden & Outdoor
  "planter", "raised bed", "garden bed", "hanging basket", "plant hanger", "trellis", "arbor",
  "weed trimmer", "hedge clipper", "pruning shears", "loppers", "garden saw", "pole saw", "tree trimmer", "branch cutter",
  "drip line", "soaker hose", "hose reel", "hose nozzle", "watering wand", "irrigation pipe", "garden timer",
  "hand trowel", "cultivator", "weeder", "dibble", "bulb planter", "soil scoop", "transplanter",
  "leaf rake", "garden rake", "bow rake", "thatch rake", "landscape rake", "hay fork", "manure fork", "compost fork", "broadfork",
  "garden cart", "utility cart", "dump cart", "yard wagon", "plant dolly", "pot mover", "hand truck", "garden kneeler", "kneeling pad",
  "bird house", "squirrel feeder", "hummingbird feeder", "suet feeder", "nesting box", "bat house", "bee hotel", "butterfly house",
  "lawn ornament", "garden statue", "gazing ball", "stepping stone", "garden path", "flagstone", "paver", "landscape rock",
  "fence post", "picket fence", "chain link fence", "privacy fence", "garden gate", "lattice panel", "fence panel", "post cap", "fence wire", "garden border",
  "fire pit", "chiminea", "outdoor grill", "barbecue", "smoker", "charcoal grill", "gas grill", "hibachi", "fire ring", "campfire",
  "patio chair", "patio umbrella", "sun shade", "outdoor rug", "outdoor cushion", "hammock stand", "outdoor sofa",
  "pool", "hot tub", "above ground pool", "pool ladder", "pool pump", "pool filter", "pool cover", "pool skimmer",
  "mailbox", "house number", "welcome sign", "address plaque", "porch light", "path light", "solar light", "landscape light", "flood light", "motion light",
  "dog house", "dog run", "pet door", "invisible fence", "pet fountain", "rabbit hutch", "chicken run", "beehive",
  "outdoor thermometer", "flag", "banner", "pennant", "windsock", "pinwheel", "garden spinner",
  // Weapons & Medieval
  "sword", "dagger", "katana", "rapier", "broadsword", "claymore", "scimitar", "saber", "machete",
  "battle axe", "tomahawk", "halberd", "spear", "javelin", "lance", "trident",
  "bow", "arrow", "crossbow", "quiver", "longbow", "compound bow", "recurve bow", "blowgun",
  "shield", "buckler", "round shield", "tower shield", "armor", "chain mail", "plate armor", "helmet", "gauntlet", "breastplate",
  "cannon", "trebuchet", "battering ram", "siege tower", "ballista", "mortar", "bomb", "grenade", "dynamite",
  "gun", "rifle", "shotgun", "pistol", "revolver", "musket", "flintlock", "blunderbuss", "cannon ball", "bullet",
  "mace", "flail", "war hammer", "morning star", "club", "baton", "staff", "bo staff", "nunchucks", "throwing star",
  "whip", "lasso", "bolas", "net", "bear trap", "snare", "tripwire", "barbed wire", "land mine", "torpedo",
  "holster", "scabbard", "sheath", "bandolier", "ammo belt", "powder horn", "ramrod", "bayonet", "brass knuckles", "switchblade",
  "scepter", "orb", "coat of arms", "crest", "heraldry",
  // Fantasy & Mythology Creatures
  "dragon", "unicorn", "phoenix", "griffin", "pegasus", "centaur", "minotaur", "medusa", "cyclops", "hydra",
  "mermaid", "merman", "siren", "kraken", "leviathan", "sea serpent", "loch ness monster", "selkie", "kelpie", "charybdis",
  "fairy", "pixie", "sprite", "nymph", "dryad", "elf", "dwarf", "gnome", "goblin", "hobbit",
  "troll", "ogre", "giant", "titan", "golem", "gargoyle", "gorgon", "harpy", "banshee", "wraith",
  "demon", "imp",
  "angel", "cherub", "seraph", "archangel", "cupid", "grim reaper", "muse", "oracle",
  "warlock", "sorcerer", "enchantress", "necromancer", "alchemist",
  "yeti", "bigfoot", "sasquatch", "chupacabra", "mothman", "thunderbird", "jackalope", "jersey devil", "wendigo",
  "chimera", "manticore", "cockatrice", "wyvern", "drake", "wyrm", "roc",
  "leprechaun", "changeling", "will-o-wisp", "djinn", "genie", "ifrit", "rakshasa", "yokai", "tengu",
  // Shapes & Symbols
  "circle", "rectangle", "oval", "diamond", "hexagon", "octagon",
  "heart", "crescent", "cross", "spiral", "helix", "infinity symbol", "peace sign", "yin yang", "ankh",
  "sphere", "cube", "cylinder", "cone", "pyramid shape", "prism", "torus", "tetrahedron", "dodecahedron", "icosahedron",
  "checkmark", "x mark", "question mark", "exclamation mark", "ampersand", "at sign", "hashtag", "dollar sign", "percent sign", "asterisk",
  "plus sign", "minus sign", "equals sign", "parenthesis", "curly brace", "slash", "backslash",
  "smiley face", "frown face", "skull and crossbones", "radioactive symbol", "biohazard symbol", "recycling symbol", "caduceus", "fleur de lis", "treble clef", "bass clef",
  "musical note", "double note", "sharp sign", "flat sign", "fermata", "rest note",
  "crown symbol", "shield shape", "badge shape", "ribbon", "medal shape", "laurel wreath", "olive branch", "rod of asclepius",
  // Art & Craft Supplies
  "paint palette", "paint tube", "canvas", "sketch pad", "drawing paper", "watercolor paper", "charcoal stick", "graphite pencil",
  "oil paint", "acrylic paint", "watercolor", "tempera paint", "spray paint", "finger paint", "face paint", "fabric paint", "glass paint", "enamel paint",
  "pastel", "oil pastel", "chalk pastel", "conte crayon", "charcoal pencil", "blending stump", "tortillon", "fixative spray", "gesso",
  "ink pen", "dip pen", "calligraphy pen", "brush pen", "felt tip pen", "gel pen", "ballpoint pen", "rollerball pen", "technical pen",
  "glitter", "sequin", "bead", "yarn", "thread", "embroidery floss", "needle", "thimble",
  "sewing machine", "bobbin", "spool", "pin cushion", "seam ripper", "rotary cutter", "cutting mat", "pattern", "fabric scissors", "pinking shears",
  "knitting needle", "crochet hook", "loom", "spinning wheel", "drop spindle", "felting needle", "tapestry needle", "darning needle", "quilting hoop", "embroidery hoop",
  "pottery wheel", "kiln", "clay", "sculpting tool", "wire armature", "plaster mold", "glaze", "bisque", "ceramic tile",
  "wood carving tool", "linoleum cutter", "printing press", "brayer", "ink roller", "block print", "screen print",
  "mod podge", "decoupage", "papier mache", "washi tape", "masking tape", "painters tape", "craft knife",
  // Medical Items
  "stethoscope", "blood pressure cuff", "otoscope", "ophthalmoscope", "reflex hammer", "tongue depressor", "pulse oximeter", "heart monitor", "ekg machine",
  "syringe", "iv bag", "iv drip", "catheter", "scalpel", "forceps", "surgical scissors", "retractor",
  "bandage", "gauze", "medical tape", "band-aid", "ace bandage", "tourniquet", "splint", "sling", "cast", "brace",
  "wheelchair", "crutch", "walker", "cane", "prosthetic", "hearing aid", "cochlear implant", "pacemaker", "defibrillator", "ventilator",
  "hospital bed", "gurney", "stretcher", "operating table", "examination table", "iv stand", "bedpan", "emesis basin", "specimen cup", "test tube",
  "petri dish", "centrifuge", "pipette", "beaker", "flask", "graduated cylinder", "bunsen burner", "test tube rack",
  "face mask", "surgical mask", "n95 mask", "face shield", "latex glove", "surgical gown", "hair net", "shoe cover",
  "pill", "capsule", "medicine bottle", "prescription pad", "pill box", "pill cutter", "medicine dropper", "inhaler",
  "x-ray", "mri scan", "ct scan", "ultrasound", "mammogram",
  "first aid kit", "ice pack", "heating pad", "hot water bottle", "epinephrine pen", "insulin pen", "glucose meter", "oxygen tank", "nebulizer", "cpap machine",
  // Containers
  "box", "crate", "barrel", "keg", "tank", "cistern", "vat",
  "jar", "bottle", "jug", "canteen", "vial", "ampule",
  "can", "tin", "pail", "tub", "basin", "pot", "cauldron", "crucible",
  "bag", "sack", "pouch", "packet", "parcel", "package", "bundle",
  "basket", "pannier", "bushel", "cask", "hogshead", "carton", "case", "container", "bin",
  "drawer", "cabinet", "cupboard", "locker", "safe", "vault", "strongbox", "lockbox", "cash box",
  "briefcase", "carry-on", "footlocker", "steamer trunk", "hat box", "cigar box",
  "trash bag", "garbage bag", "grocery bag", "paper bag", "shopping bag", "gift bag", "gift box", "shipping box", "moving box", "storage bin",
  // Fabrics & Materials
  "cotton", "silk", "wool", "linen", "denim", "leather", "suede", "velvet", "satin", "chiffon",
  "polyester", "nylon", "spandex", "rayon", "acrylic", "flannel", "corduroy", "tweed", "cashmere",
  "burlap", "muslin", "cheesecloth", "felt", "organza", "tulle", "taffeta", "brocade",
  "lace", "crochet", "knit", "woven", "patchwork", "applique", "cross stitch",
  "wood", "plywood", "particleboard", "hardwood", "softwood", "lumber", "timber", "log", "plank",
  "metal", "steel", "copper", "brass", "bronze", "aluminum", "gold", "silver",
  "crystal", "porcelain", "ceramic", "terracotta", "stoneware", "earthenware", "bone china", "fiberglass", "plexiglass",
  "rubber", "silicone", "plastic", "foam", "styrofoam", "cardboard", "wax", "paraffin",
  // Jewelry
  "ring", "engagement ring", "wedding ring", "class ring", "signet ring", "mood ring", "toe ring", "nose ring", "belly ring", "thumb ring",
  "necklace", "pendant", "choker", "locket", "medallion", "charm", "amulet", "talisman", "rosary",
  "bracelet", "bangle", "cuff", "charm bracelet", "friendship bracelet", "tennis bracelet", "link bracelet", "beaded bracelet", "leather bracelet", "wristwatch",
  "earring", "stud earring", "hoop earring", "drop earring", "chandelier earring", "clip-on earring", "ear cuff", "pearl earring", "diamond earring",
  "brooch", "cufflink", "tie pin", "tie clip", "lapel pin", "cameo", "fibula", "anklet", "body chain",
  // Miscellaneous Common Nouns
  "fire", "smoke", "flame", "ember", "ash", "spark", "bonfire", "firework", "explosion",
  "ice", "steam", "bubble", "wave", "splash", "ripple", "whirlpool",
  "earth", "soil", "mud", "dust",
  "light", "shadow", "glow", "beam", "ray", "spectrum", "reflection",
  "treasure map", "world map", "road map", "star chart", "blueprint", "floor plan", "schematic", "diagram",
  "streamer", "garland", "wreath", "lei", "corsage", "boutonniere",
  "mask", "costume", "disguise", "wig", "fake mustache", "clown nose", "tattoo", "henna",
  "award", "certificate", "diploma", "plaque",
  "coin", "bill", "credit card", "money",
  "ticket", "coupon", "gift card", "postage stamp", "passport", "license", "boarding pass", "receipt",
  "book", "magazine", "newspaper", "comic book", "graphic novel", "manga", "pamphlet", "brochure", "catalog", "menu",
  "letter", "greeting card", "invitation", "birthday card", "valentine", "love letter", "note",
  "sign", "placard", "exit sign", "stop sign", "yield sign", "speed limit sign",
  "road", "highway", "intersection", "roundabout", "cul-de-sac", "alley", "lane", "path", "trail", "sidewalk",
  "crosswalk", "speed bump", "pothole", "manhole", "storm drain", "curb", "gutter",
  "parking lot", "parking meter", "parking garage", "toll booth", "gas station", "car wash", "drive through", "bus stop",
  "playground", "swing", "see-saw", "monkey bars", "climbing wall", "zip line",
  "park", "garden", "courtyard", "plaza", "promenade", "boardwalk",
  "cemetery", "tombstone", "gravestone", "mausoleum", "crypt", "coffin", "casket", "urn", "memorial", "headstone",
  "circus", "carnival", "fair", "amusement park", "theme park", "haunted house",
  "zoo", "petting zoo", "wildlife reserve", "botanical garden",
  "seashell", "driftwood", "sea glass",
  "rope bridge", "suspension bridge", "covered bridge", "stone bridge", "wooden bridge", "footbridge", "viaduct",
  "well", "water pump", "grain silo", "hay bale",
  "cell tower", "radio tower", "transmission tower", "power line", "telephone pole", "traffic cone", "road barrier",
  "observatory", "planetarium",
  // Additional Drawable Words
  "aardvark", "barn owl", "bengal tiger", "brown bear", "bull shark",
  "canada goose", "emperor penguin", "fennec fox", "fruit bat", "garden spider",
  "german shepherd", "giant squid", "gila monster", "golden eagle", "golden retriever",
  "great dane", "great white shark", "green iguana", "grizzly cub",
  "jack rabbit", "king penguin", "labrador", "leaf insect",
  "leopard gecko", "mountain goat", "mountain lion", "ocelot",
  "peregrine falcon", "pine marten",
  "prairie dog", "praying mantis", "pronghorn",
  "quetzal", "rainbow trout", "red fox", "red panda",
  "ring-tailed lemur", "river otter", "sand crab", "scarlet macaw",
  "siamese cat", "siberian husky", "snow leopard", "snowy owl", "spider monkey",
  "sugar glider", "tabby cat", "tapir",
  "timber wolf", "tree frog", "water buffalo", "white tiger", "wild horse",
  "zebra finch",
  "apple pie", "apple sauce", "baked beans", "banana bread",
  "barbecue sauce", "beef stew", "beef jerky",
  "blueberry muffin", "blueberry pie",
  "bread pudding", "breakfast burrito", "broccoli soup",
  "brown rice", "butternut squash", "butterscotch",
  "candy apple", "candy bar", "caramel apple", "carrot cake",
  "celery stick", "cheese pizza", "cherry pie",
  "cherry tomato", "chicken breast", "chicken noodle soup", "chicken salad", "chicken tender",
  "chili dog", "chocolate cake", "chocolate chip", "chocolate milk",
  "cinnamon stick", "coconut cream", "coconut milk",
  "cookie dough", "corn chip", "corn muffin", "corn on the cob",
  "crab leg", "cracker", "cream pie",
  "deviled egg",
  "dinner roll", "dipping sauce", "dried fruit",
  "egg noodle", "egg salad", "fish fillet",
  "fish sandwich", "flatbread", "french onion soup", "fried plantain",
  "frozen dinner", "fruit cup", "fruit salad", "fruit tart", "garlic bread",
  "garlic knot", "ginger cookie", "glazed donut", "goat cheese",
  "grape jelly", "green salad", "green tea", "grilled chicken",
  "grilled fish", "grilled steak", "ground beef", "ham sandwich",
  "hawaiian pizza", "honey bun", "honey jar", "hot sauce",
  "iced coffee", "jam jar", "key lime pie",
  "kettle corn", "lamb chop", "layer cake", "lemon bar",
  "lemon meringue", "lemon slice", "lobster tail", "mac and cheese",
  "maple syrup", "meat pie", "meatball sub", "melon slice", "mint leaf",
  "mixed nuts", "mozzarella stick", "naan bread", "olive oil",
  "onion soup", "orange slice", "pancake stack",
  "pasta salad", "peach cobbler", "peanut butter", "pecan pie",
  "pickle", "pie crust", "pineapple ring",
  "pita bread", "pizza slice", "pork belly", "pork bun",
  "pot sticker", "potato soup", "potato wedge",
  "pumpkin pie", "pumpkin seed",
  "raisin", "raisin bread", "ranch dressing", "red velvet cake", "red wine",
  "rice noodle", "rice pudding", "roast chicken", "roast turkey",
  "rye bread", "salad dressing", "salmon fillet",
  "sesame seed", "shaved ice", "shrimp tempura", "slice of bread",
  "smoked salmon", "soda can", "sourdough loaf",
  "soy sauce", "spinach dip",
  "strawberry jam", "stuffed pepper", "sugar cookie", "sugar cube",
  "sushi roll", "sweet corn", "taco shell", "toast",
  "tomato sauce", "tomato soup", "trail mix", "turkey sandwich", "vanilla ice cream",
  "vegetable soup", "veggie burger", "waffle cone", "walnut", "wheat bread",
  "white bread", "white rice", "white wine", "yogurt cup", "zucchini bread",
  "baby bottle", "baby monitor", "baby stroller", "back brace",
  "balance scale", "ball of yarn", "beach towel",
  "birthday candle", "boat anchor", "body pillow",
  "book cover", "bottle cap", "bowling pin",
  "bread box", "candle wax", "candy dish",
  "car battery", "car door", "car engine", "car key", "car seat",
  "car tire", "car wheel", "card deck", "cargo net",
  "cat collar", "chess clock",
  "cigar", "cigarette",
  "coal", "coat hanger",
  "coffee bean", "coffee cup", "coffee mug",
  "color wheel", "cookie jar",
  "cooling rack", "cork",
  "cotton reel",
  "crystal ball",
  "cup holder", "curtain rod",
  "disco ball",
  "dog bone", "dog collar", "dog leash", "dog tag",
  "doll house", "door hinge",
  "door stopper",
  "dream catcher", "dress form",
  "dust mask",
  "ear muff",
  "eye dropper", "eye mask",
  "feather", "feather boa",
  "foam finger",
  "folding fan", "food tray", "foot pedal",
  "footprint", "fossil",
  "fruit basket",
  "fur coat", "garden arch",
  "garden glove", "gas can", "gas mask",
  "gear", "gem stone", "gift bow", "gift wrap",
  "glass bottle", "glass jar",
  "gold bar", "gold coin", "gold nugget", "golf bag", "golf tee",
  "gourd", "grape vine",
  "grill grate",
  "guitar case", "guitar pick", "guitar string",
  "gum ball", "gum ball machine",
  "gym bag",
  "hand bell", "hand fan", "hand mirror",
  "handcuff", "hard hat",
  "hay stack", "head lamp",
  "heart locket", "heat lamp",
  "honey comb", "hood ornament",
  "horse saddle", "horse shoe",
  "hot plate",
  "house key", "house plant", "hub cap",
  "hunting knife",
  "ice block", "ice bucket", "ice chest",
  "ice pick", "ice sculpture",
  "incense burner", "incense stick",
  "iron gate",
  "jack-o-lantern", "jade stone",
  "jingle bell", "juice box",
  "kayak paddle", "key card",
  "kitchen apron", "kitchen counter",
  "kitchen faucet", "kitchen knife", "kitchen sink",
  "kitchen towel",
  "knee brace",
  "lamp shade",
  "laundry detergent",
  "leather belt", "leather boot", "leather glove", "leather jacket",
  "lens cap",
  "life buoy", "life preserver",
  "log cabin",
  "magic carpet", "magic hat", "magic lamp", "magic wand",
  "magnet", "maple leaf", "marble",
  "marble statue",
  "match box", "match stick",
  "megaphone",
  "metronome",
  "milk bottle", "milk carton", "milk jug",
  "mini fridge", "moat",
  "model airplane", "model boat", "model car", "model house",
  "model rocket", "model train", "money bag",
  "moon rock",
  "motor", "motorcycle helmet",
  "movie reel", "movie screen", "movie ticket",
  "mug handle",
  "nail file",
  "nest",
  "night cap", "night sky",
  "oak leaf", "oar",
  "ocean wave", "oil barrel", "oil can",
  "oil painting", "old book",
  "open book", "opera mask",
  "origami bird",
  "ornament",
  "paddle",
  "paint can", "paint splatter",
  "palette knife", "palm frond",
  "paper chain", "paper cup", "paper fan", "paper lantern", "paper plate",
  "parasol",
  "party hat", "party horn", "party streamer",
  "patch",
  "paw print", "pea pod",
  "peacock feather", "peanut shell",
  "pearl", "pearl necklace",
  "pedal", "peg",
  "pen cap", "pen nib", "pencil lead",
  "pendulum",
  "penny",
  "perfume bottle",
  "pet carrier", "petal",
  "phone case", "phone charger",
  "photo album", "piano key",
  "pine cone", "pine needle", "ping pong ball", "pipe cleaner",
  "pirate flag", "pirate hat", "pirate ship",
  "pocket knife",
  "police badge", "police hat",
  "pool ball", "pool cue",
  "popsicle stick", "porcelain doll",
  "port hole",
  "pot lid",
  "propeller",
  "pulley", "puppet string",
  "puzzle piece",
  "quartz crystal",
  "rabbit foot",
  "racing flag",
  "rag doll", "rain cloud",
  "raw diamond", "reading lamp", "record album",
  "red carpet", "red wagon",
  "reflector",
  "rocking horse",
  "rubber ball", "rubber duck", "rubber mallet", "rubber stamp",
  "ruby gem", "rudder",
  "running track",
  "saddle bag",
  "safety harness", "safety net", "safety pin", "safety vest",
  "sail",
  "sailor hat",
  "salt lamp", "sand bag",
  "sapphire gem",
  "school bell", "school bus",
  "scroll",
  "sea foam", "sea shell",
  "seat belt", "seat cushion", "seed packet",
  "serving bowl", "serving platter",
  "sewing basket", "sewing kit",
  "shadow puppet", "shark fin", "shark tooth",
  "ship anchor", "ship helm", "ship mast", "ship wheel",
  "shirt collar", "shirt pocket",
  "shoe box", "shoe horn", "shoe lace",
  "shopping cart",
  "shower cap", "shower curtain",
  "signal flare",
  "silver bar", "silver coin",
  "sketch book",
  "ski mask", "ski slope",
  "sky lantern",
  "sleeping mask",
  "smoke ring", "smoking pipe",
  "snap button",
  "snow angel", "snow cone", "snow fort",
  "soap bar", "soap bubble",
  "soccer cleat",
  "soda bottle",
  "spark plug", "speaker cone",
  "spider web", "spike", "spindle",
  "sponge mop", "spool of thread", "spoon rest",
  "sport jersey", "sports bag",
  "spray can", "spring coil",
  "sprinkler head", "spy glass",
  "squeeze bottle",
  "stack of books", "stack of coins",
  "stage curtain", "stage light",
  "stake", "stalk",
  "stand mixer",
  "steam engine", "steam iron",
  "steel beam", "steel cable",
  "sticker", "stirrup",
  "stone wall",
  "storage box", "storage crate", "storage jar",
  "stove burner",
  "straw hat",
  "string light",
  "stump",
  "sugar cane",
  "sun visor", "sundress", "sunflower seed",
  "swan lake", "sweater vest", "sweet pea",
  "swim ring",
  "sword blade",
  "table leg", "table runner",
  "tail feather",
  "tape dispenser", "tape roll",
  "target board",
  "tassel", "tea bag", "tea cup", "tea leaf",
  "tea set", "telescope lens",
  "tent pole", "tent stake",
  "thatch roof", "theater curtain", "theater mask",
  "thick rope",
  "thread spool",
  "ticket booth", "ticket stub",
  "tile floor", "tile mosaic",
  "tin can", "tin foil", "tin roof", "tinsel",
  "toast rack",
  "tomato vine", "tongue depressor stick",
  "tool bag",
  "tooth fairy", "torch flame",
  "totem",
  "tour bus",
  "tower crane",
  "toy block", "toy drum", "toy horse", "toy piano",
  "train car", "train engine", "train track",
  "trampoline net",
  "trap door", "travel bag", "travel mug",
  "tree bark", "tree branch", "tree house", "tree ring",
  "tree root", "tree stump", "tree trunk",
  "tribal mask", "tripod",
  "trophy cup",
  "tropical fish", "truck bed",
  "trumpet bell",
  "tulip bulb",
  "tunnel entrance", "turkey feather",
  "tv antenna", "tv remote", "tv screen", "tv tray",
  "twig", "twine ball",
  "umbrella handle",
  "unicorn horn",
  "vacuum hose",
  "valve",
  "vinyl record", "violin bow", "violin string",
  "volcanic rock",
];